### ISSUE TITLE
templates

### ISSUE THREAD

**Issue by MalcolmMielle** [RainerKuemmerle/g2o#112]
Hej,

Being a newcomer to g2o and trying to dig in the code to understand it, I was wondering if the use of template as well as maybe boost graph library would not be a lot easier to use and maintain ? I think the result would be the same but I'm wondering if there is a particular reason for not using templates ?

Thanks a lot

**Comment by felixendres** [comment]
g2o does make heavy use of templates, e.g., for the Edge and Vertex base classes.

Everyone I know who used the boost graph library, said it was very complicated to use.
