### ISSUE TITLE
g2o::EdgeSim3 error LNK2001 in vs2013Project

### ISSUE THREAD

**Issue by kingstarcraft** [RainerKuemmerle/g2o#116]
hello, I had added all the g2o lib to my vs2013 project, but  I still got the error like this:  error LNK2001: unresolved external symbol "public: __cdecl g2o::EdgeSim3::EdgeSim3(void)" when I write " g2o::EdgeSim3\* en = new g2o::EdgeSim3()" in my project .

**Comment by xuetl** [comment]
I have the same problem, do you have solved it?

**Comment by xuetl** [comment]
@kingstarcraft  I have the same problem, do you have solved it?

**Comment by kingstarcraft** [comment]
yes,but I have forgotten.
