### ISSUE TITLE
Jacobian matrix computation in g2o

### ISSUE THREAD

**Issue by ethcamera** [RainerKuemmerle/g2o#122]
Hi Author,

I am new to g2o, would like to know how is Jacobian computed/handled in g2o framework.

From ceres solver, the Jacobian matrix is computed using class AutoDiffCostFunction, would like to know how g2o handle this.

Thank a lot.

**Comment by izhengfan** [comment]
Jacobian is handled by `linearizeOplus()` method, e.g. [types_six_dof_expmap.cpp ](https://github.com/RainerKuemmerle/g2o/blob/master/g2o/types/sba/types_six_dof_expmap.cpp#L274).

If this method is not implemented, g2o will compute Jacobian by numerical methods.
