### ISSUE TITLE
Cholesky failure

### ISSUE THREAD

**Issue by elmuz** [RainerKuemmerle/g2o#125]
Hi guys what does the following error message refers to: "Cholesky failure, writing debug.txt (Hessian loadable by Octave)"?
I mean, I know what a Cholesky decomposition is, but what's wrong with my hypergraph so that it throws this exception?
At first it was working ok, then I tuned some edges information matrices and suddenly it doesn't like the it anymore. Any ideas on that?
Thank you

**Comment by izhengfan** [comment]
You may try reviewing whether something wrong with the float point computation and some Nan number existing in your information matrix, Jacobian or somewhere else.

**Comment by elmuz** [comment]
Some info:
- Keeping standard information matrix it never throws any exception (so that must be the reason).
- I checked that all edges have SPD information matrix, both using integrated g2o function and Eigen's.
- In the debug.txt, CTRL+F for "NaN" doesn't return any occurrance. Is there any better way to check numerical problems?
Thank you

**Comment by felixendres** [comment]
In my experience, this also happens if the statistical errors get large, e.g. when the optimizer diverges. The statistical error also gets large if you use large values in the information matrix.

**Comment by elmuz** [comment]
Thank you @felixendres that's a nice idea.

**Comment by RainerKuemmerle** [comment]
Closing this for now. Please provide a specific example if the error occurs again.

**Comment by dingshuoshuo** [comment]
My problem is the float data error in the info matrix
