### ISSUE TITLE
Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by khaire1111** [RainerKuemmerle/g2o#130]
I have issue pls tell me anyone

I created one custom framework for social login it's working as debug mode but whenever I build framework for release mode it gives error like

Undefined symbols for architecture x86_64:

"OBJC_CLASS$_Social", referenced from:

objc-class-ref in ViewController.o

objc-class-ref in DetailViewController.o

ld: symbol(s) not found for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

I do not understand what is happaning on release mode

I write singleton class of Social

and it has one method as

+(instancetype)methodSocial { }

**Comment by RainerKuemmerle** [comment]
I do not see any relation to g2o.
