### ISSUE TITLE
Generating noisy spheres

### ISSUE THREAD

**Issue by harsanyika** [RainerKuemmerle/g2o#136]
Hello!

I'm trying the generate multiple spheres with the same noise parameters, but different RANDOM Gaussian noise. However running ./create_sphere ... with the same parameters always gives the exact same result.

How can I solve this problem?

**Comment by RainerKuemmerle** [comment]
Hi,

I quickly added a command line flag for create_sphere which allows to use randomized seeds.
see 9d4509271d2180040abf6225f75dfe6118ff4d04

Best
Rainer

**Comment by harsanyika** [comment]
Hi,

That was fast. Thank you.
