### ISSUE TITLE
How to generate the informational matrix?

### ISSUE THREAD

**Issue by EPiress** [RainerKuemmerle/g2o#141]
Hi,

I have been trying to implement a graph-SLAM with a drone (no odometry). How can i compute the Upper Triangular Informational Matrix  to use in the EDGE_SE2 variable?
Sorry, but I am really new to graph-SLAM, and I'd really appreciate your help!

**Comment by RainerKuemmerle** [comment]
The information matrix is the inverse of the covariance matrix associated to the your measurement(). It reflects the uncertainty of the measurements.
