### ISSUE TITLE
CMake Error: The following variables are used in this project, but they are set to   NOTFOUND. 

### ISSUE THREAD

**Issue by barnett88** [RainerKuemmerle/g2o#147]
Run catkin_make command error
CMake Error: The following variables are used in this project, but they are set to

NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
G2O_SOLVER_CHOLMOD
linked by target "svo" in directory /root/ros_catkin_ws/src/rpg_svo/svo

-- Configuring incomplete, errors occurred!
See also "/root/ros_catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/root/ros_catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

How can I fix it?

**Comment by RainerKuemmerle** [comment]
Did you install libsuitesparse-dev? Otherwise the Cholmod solver is not built.

**Comment by barnett88** [comment]
Has been resolved, thank you.
