### ISSUE TITLE
Segmentation fault when optimize is called

### ISSUE THREAD

**Issue by arihantb2** [RainerKuemmerle/g2o#153]
Program received signal SIGSEGV, Segmentation fault in g2o::SparseOptimizer::optimize(int, bool) ().

I have verified that the vertices and edges are added correctly by placing checks in my code. I have also checked the number of vertices and edges before calling the optimize function.

**Comment by arihantb2** [comment]
![g2o_seg_fault](https://cloud.githubusercontent.com/assets/10983214/22662644/9635bb40-ec5e-11e6-8120-50bc93d29eef.png)

**Comment by arihantb2** [comment]
The program seg faults when I call g2o::SparseOptimizer::clear() also. For some reason, it is not able to reference the vertices and edges

**Comment by corenel** [comment]
@arihantb2 
Could you tell me how you solve this problem?
I've met this situation too.
