### ISSUE TITLE
What the abbreviation SE2 stands for?

### ISSUE THREAD

**Issue by neumann89** [RainerKuemmerle/g2o#181]
Hi!
You mention that SE2 is the position x,y and orientation theta. But why is it called "SE"? I couldn't find any explanation for it. Could you please add to the documentation and code comments what the abbreviation SE2 stands for?

**Comment by felixendres** [comment]
It's an abbreviation for the [Special Euclidean group](https://en.wikipedia.org/wiki/Euclidean_group#Direct_and_indirect_isometriesl) for 2-dimensional space.

SE2 contains the rigid body motions in 2D.

**Comment by csp256** [comment]
I suggest Tom Drummond's notes for learning more about Lie algebras / groups in computer vision:

https://dl.dropboxusercontent.com/u/23948930/Papers/3DGeometry.pdf

The relevant part begins in chapter 2, but chapter 1 is good too.

**Comment by neumann89** [comment]
Thank you very much!
