### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by jasjuang** [RainerKuemmerle/g2o#194]
First of all, thanks for the awesome library. I am integrating g2o into Microsoft's [vcpkg](https://github.com/Microsoft/vcpkg/). The problem is the current latest release that was released last year does not compile on windows. However, I am able to compile g2o successfully with the latest master. Could you make a new release that contains the windows compilation fix?

**Comment by mojovski** [comment]
Hi,
I tested the current master on windows with VS2015 and it ran well.

**Comment by RainerKuemmerle** [comment]
Here we go. Current master tagged as a release version.
