### ISSUE TITLE
Double free or corruption when calling constructor with parameters of CameraParameters

### ISSUE THREAD

**Issue by FinleyPan** [RainerKuemmerle/g2o#205]
The terminal asserted **double free or corruption(out)** when calling constructor with parameters of CameraParameters:
`g2o::CameraParameters* camera = new g2o::CameraParameters (K.at<double> ( 0,0 ), Eigen::Vector2d ( K.at<double> ( 0,2 ), K.at<double> ( 1,2 ) ), 0);  `
   `camera->setId ( 0 );`
  `  optimizer.addParameter ( camera );  `
  But it ran properly when I employed default constructor:
`g2o::CameraParameters* camera = new g2o::CameraParameters ();`

**Comment by dingjiangang** [comment]
i met this problem again, so how to work it

**Comment by dingjiangang** [comment]
@FinleyPan 
i met this problem again, so how to work it

**Comment by jarvisyjw** [comment]
@dingjiangang Have you solved it? I also encountered this problem.
