### ISSUE TITLE
Raspberry Pi3：c++: error: unrecognized command line option ‘-msse4.2’

### ISSUE THREAD

**Issue by bonne658** [RainerKuemmerle/g2o#218]
Hello,when I make g2o on Raspberry Pi3, I get the error "c++: error: unrecognized command line option ‘-msse4.2’". 
Is there any solution to use msse4.2 on Raspberry Pi3? 
Thanks.

**Comment by jlblancoc** [comment]
Added a PR #219 to fix this one. Cheers.

**Comment by RainerKuemmerle** [comment]
Merged the PR. Please update if it does not fix the problem.
