### ISSUE TITLE
Dose G2O support dynamic edge type?

### ISSUE THREAD

**Issue by pangfumin** [RainerKuemmerle/g2o#224]
Hi , thank you for sharing this great code. 
I am trying to apply G2O to solve some optimization problem where the number of vertexes of an edge is variable and not known before construct this edge. I want to know whether G2O support dynamic edge type?
Thank you again.
Pang @Beijing

**Comment by RainerKuemmerle** [comment]
Yes, it is supported (might be a bit late reply). But have a look at https://github.com/RainerKuemmerle/g2o/blob/master/g2o/types/slam2d/edge_se2_lotsofxy.h
