### ISSUE TITLE
cs.h: No such file or directory

### ISSUE THREAD

**Issue by pwnyholm** [RainerKuemmerle/g2o#23]
When trying including g2o/solvers/csparse/linear_solver_csparse.h, like is done in  tutorial_slam2d, I get the following error from csparse_helper.h when compiling:

cs.h: No such file or directory

It seems that rather than including cs.h, csparse_helper should be looking to include suitesparse/cs.h?

Do you have any insight on this?

Thanks

**Comment by chenchen2015** [comment]
Had the same issue. Got it resolved by reinstalling `SuiteSparse` to `/usr/local`, which does not seems to be the default behavior. Here are the steps:

1. Checkout [SuiteSparse](https://github.com/jluttine/suitesparse) `git clone https://github.com/jluttine/suitesparse` or download from [their website](http://faculty.cse.tamu.edu/davis/suitesparse.html) and unzip.
2. Install to `/usr/local` with `sudo make install INSTALL=/usr/local`, append `-j4` to the end for example to run 4 jobs in parallel to accelerate as needed
3. Add the following cmake script to your `CMAKE_MODULE_PATH`
```cmake
# FindCSparse.cmake, put under /usr/share/cmake-{version}/Modules
# Look for csparse and set package handle args
FIND_PATH(CSPARSE_INCLUDE_DIR NAMES cs.h
  PATHS
  /usr/include/suitesparse
  /usr/include
  /opt/local/include
  /usr/local/include
  /sw/include
  /usr/include/ufsparse
  /opt/local/include/ufsparse
  /usr/local/include/ufsparse
  /sw/include/ufsparse
)

FIND_LIBRARY(CSPARSE_LIBRARY NAMES cxsparse
  PATHS
  /usr/lib
  /usr/local/lib
  /opt/local/lib
  /sw/lib
)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(
  CSPARSE DEFAULT_MSG
  CSPARSE_INCLUDE_DIR CSPARSE_LIBRARY
)
```
4. Add `find_package( CSparse REQUIRED )` to your `CMakeLists.txt` and you should have `CSPARSE_INCLUDE_DIR` and `CSPARSE_LIBRARY` available
