### ISSUE TITLE
g2o_viewer

### ISSUE THREAD

**Issue by jsYangCode** [RainerKuemmerle/g2o#231]
Ubuntu 16.04, when i run the g2o_viewer,some problem occur. i cannot solve this problem myself. could someone help me? thank you very very much.
![2017-12-14 15-04-33](https://user-images.githubusercontent.com/34529308/33982676-470a615a-e0ec-11e7-8414-eb520d884be4.png)

**Comment by CCB307** [comment]
Did you compile g2o_viewer with Qt5? I have a error when I compile g2o_viewer.
![image](https://user-images.githubusercontent.com/18183832/34663576-718029e2-f492-11e7-8de7-8e6c48819608.png)

**Comment by osiz-blockchainapp** [comment]
I am facing the same error, did you got any solution? 
/usr/lib/x86_64-linux-gnu/qt5/bin/uic: symbol lookup error: /usr/lib/x86_64-linux-gnu/qt5/bin/uic: undefined symbol: qt_qhash_seed
