### ISSUE TITLE
error: no member named 'updateGL' in 'g2o::G2oQGLViewer'

### ISSUE THREAD

**Issue by yurivict** [RainerKuemmerle/g2o#237]
```
/usr/ports/math/g2o/work/g2o-d652b0b/g2o/apps/g2o_viewer/main_window.cpp:111:11: error: no member named 'updateGL' in 'g2o::G2oQGLViewer'
  viewer->updateGL();
  ~~~~~~  ^
```

libQGLViewer-2.7.1

**Comment by Occup** [comment]
I didn't check all the code associated,
Just change All "updateGL()" in g2o source code to "update",
it works for me

**Comment by RainerKuemmerle** [comment]
Related to QGLViewer >= 2.7
a8ea37fcf20f902ac91b8b6585f917ea671c807b

**Comment by matheecs** [comment]
Please see the [Change Log](http://libqglviewer.com/changeLog.html)
> Using update() instead of updateGL() is one of them

**Comment by yurivict** [comment]
Thanks!
