### ISSUE TITLE
Please make examples work without the need to tweak them

### ISSUE THREAD

**Issue by yurivict** [RainerKuemmerle/g2o#244]
I have g2o installed, but examples can't be immediately built because of missing paths and wrong names.

For example, CMakeLists.txt in ```g2o/examples/sphere``` should look something like this to work:

```
SET(CMAKE_CXX_STANDARD 11)

INCLUDE_DIRECTORIES(${CMAKE_INSTALL_PREFIX}/include ${CMAKE_INSTALL_PREFIX}/include/eigen3)
LINK_DIRECTORIES(${CMAKE_INSTALL_PREFIX}/lib)

ADD_EXECUTABLE(create_sphere
  create_sphere.cpp
)

SET_TARGET_PROPERTIES(create_sphere PROPERTIES OUTPUT_NAME create_sphere${EXE_POSTFIX})
TARGET_LINK_LIBRARIES(create_sphere g2o_core g2o_types_slam3d g2o_stuff)
```

**Comment by RainerKuemmerle** [comment]
Examples are meant to be built from the full source tree not against an installed version.
There is a cmake variable which controls whether the examples should be build or not.
Hope this helps.
