### ISSUE TITLE
scale optimization in object SLAM

### ISSUE THREAD

**Issue by DouglasCBO** [RainerKuemmerle/g2o#267]
Hi @RainerKuemmerle,

I am working with object SLAM and I want to optimize the map scale simultaneously with cameras, points and known objects in the scene. Since the scale is isotropic (1D) and it is the same for all objects, I think that I need one vertex for the scale parameter linking with all object SE3 vertices. My optimization formulation is almost the same as the work by [Gálvez-López et al.](https://drive.google.com/file/d/1LqPMkggUMCgPqGuIY5e02UjQdwJs1nMU/view) (see the Bayesian network on page 5, Figure 4b). 

The problem is that, as far as I know, this is not possible to implement with the library. I studied the source-code and found that the marginalized flag, in practice, classifies a vertex as Landmark or Pose. All vertices of the same "class" must have the same dimension, thus the library supports 2 different vertex dimensions. However, in my formulation, I have 3 different vertex dimension (3D: points, 6D: cameras and objects, 1D: scale).

The only way that I found to implement something like that is using Sim3 for objects and cameras and link Sim3 object vertices with a scale constraint edge (e = |s1 - s2|). For the cameras, the scale component will be kept fixed. I think this formulation very ugly and it doesn't guarantee the same scale.

Can you (or someone else) please give me an idea?

**Comment by standmit** [comment]
Hi @DouglasCBO 
Could you provide sample code for your implementation? Or maybe you found a better solution?
