### ISSUE TITLE
Nothing displayed in g2o_viewer

### ISSUE THREAD

**Issue by Bardo91** [RainerKuemmerle/g2o#272]
I am trying to visualize my graph using the g2o_viewer but what I see is just the coordinate system.
![image](https://user-images.githubusercontent.com/3602335/39657325-211f6bd6-5007-11e8-9ded-fc917f5921cb.png)
This is my file:
[g2o_graph.g2o.tar.gz](https://github.com/RainerKuemmerle/g2o/files/1976166/g2o_graph.g2o.tar.gz)

I tried the viewer with the venice dataset (http://ais.informatik.uni-freiburg.de/projects/datasets/g2o-datasets/), but It still the same.
![image](https://user-images.githubusercontent.com/3602335/39657351-4cec67b4-5007-11e8-898e-9889d61a855b.png)

What I do is run the viewer by callin `g2o_viewer` in the command line, and then using the drop down menu I load the files. Is there something that I am missing? or should it work just with loading the files?

**Comment by Zander-yang** [comment]
Did you define the vertex and edge by yourself and load type， solver via a share library(.so)？ I loaded the .g2o file generated by example/tutorial_slam2d. The result of g2o_viewer seems like yours.

**Comment by YangSiri** [comment]
Hi,
I have the same question. It says there are some vertexs and some measurements, but there is nothing displayed. I used self-defined edge and also SE3Edge. But i tried other people's *.g2o. It works fine. Do you have any new comments?

Looking forward to your help. Thanks.

**Comment by RainerKuemmerle** [comment]
On custom types you need to provide the classes to draw them. See the existing types for examples on how to draw.
