### ISSUE TITLE
Doubt in Jacobian calculation

### ISSUE THREAD

**Issue by anirudt** [RainerKuemmerle/g2o#273]
Hi,

I just had a doubt with respect to the Jacobian calculation in the following lines:
https://github.com/RainerKuemmerle/g2o/blob/4841bb0c672dc103324174725c156dc7a89476fb/g2o/types/sba/types_six_dof_expmap.cpp#L557

I've understood how the partial derivative is calculated with respect to the translational part of the pose, but I don't understand how the partial derivatives have been calculated with respect to the rotational part. If it is the quaternion that is being expressed, could someone help me with the math?

As far as I know,

x = **R**X + **t**, now how can we express partial derivatives with respect to q (that has a one-to-one relation with R)?

**Comment by LeeKeifon** [comment]
@anirudt u can calculate the jacobian through the partial derivative with respect to the position of the point(the point after transformation),but not with respect to the translation part and rotate part.
