### ISSUE TITLE
undefined reference to `g2o::OptimizationAlgorithmLevenberg::OptimizationAlgorithmLevenberg(g2o::Solver*)'

### ISSUE THREAD

**Issue by voyage19941119** [RainerKuemmerle/g2o#274]
My error info:

[ 94%] Linking CXX executable ../bin/crowdsource
../lib/libcrowdsource_lane.so: **## undefined reference to `g2o::OptimizableGraph::addVertex(g2o::HyperGraph::Vertex*, g2o::OptimizableGraph::Data*)'**
../lib/libcrowdsource_lane.so: ## **undefined reference to `g2o::OptimizationAlgorithmLevenberg::OptimizationAlgorithmLevenberg(g2o::Solver*)'**
collect2: error: ld returned 1 exit status
  
I have linked libg2o_core.so, and other references are fine after link g2o_core
Thanks for reply  @RainerKuemmerle

**Comment by voyage19941119** [comment]
I have fix this using another version of g2o

**Comment by simonprovost** [comment]
@voyage19941119  which one ?

**Comment by sjulier** [comment]
Context?
