### ISSUE TITLE
linearSolver errors, code copied from sba_demo.cpp

### ISSUE THREAD

**Issue by antithing** [RainerKuemmerle/g2o#279]
Hi, i am on windows, and am trying to compile some code that uses g2o.

I have copied this code from `sba_demo.cpp`:

```
g2o::SparseOptimizer optimizer;
	optimizer.setVerbose(false);
	std::unique_ptr<g2o::BlockSolver_6_3::LinearSolverType> linearSolver;

	linearSolver = g2o::make_unique<g2o::LinearSolverCholmod<g2o::BlockSolver_6_3::PoseMatrixType>>();


	g2o::OptimizationAlgorithmLevenberg* solver = new g2o::OptimizationAlgorithmLevenberg(
		g2o::make_unique<g2o::BlockSolver_6_3>(std::move(linearSolver)));

	optimizer.setAlgorithm(solver);
```

this line:

`g2o::OptimizationAlgorithmLevenberg* solver = new g2o::OptimizationAlgorithmLevenberg(
		g2o::make_unique<g2o::BlockSolver_6_3>(std::move(linearSolver)));`

gives me an error:

`"g2o::OptimizationAlgorithmLevenberg::OptimizationAlgorithmLevenberg(const g2o::OptimizationAlgorithmLevenberg &)" (declared implicitly) cannot be referenced -- it is a deleted function	`

Why would this code work in the demo, but not in my function?
 I am on the latest branch, visual studio 2015, windows 10.

Thank you.

**Comment by antithing** [comment]
Ah, of course I found it soon after posting. I needed to add:

`#include "g2o/solvers/cholmod/linear_solver_cholmod.h"`

The errors have gone. One more thing, i am attempting to run some third party code, and have replaced:

```
 g2o::SparseOptimizer optimizer;
    optimizer.setVerbose(false);
    g2o::BlockSolver_6_3::LinearSolverType* linearSolver;
    linearSolver = new g2o::LinearSolverCholmod<g2o::BlockSolver_6_3::PoseMatrixType>();
    g2o::BlockSolver_6_3* solver_ptr = new g2o::BlockSolver_6_3(linearSolver);
    g2o::OptimizationAlgorithmLevenberg* solver = new g2o::OptimizationAlgorithmLevenberg(solver_ptr);
```

which would not compile, with:


```
	g2o::SparseOptimizer optimizer;
	optimizer.setVerbose(false);
	std::unique_ptr<g2o::BlockSolver_6_3::LinearSolverType> linearSolver;

	linearSolver = g2o::make_unique<g2o::LinearSolverCholmod<g2o::BlockSolver_6_3::PoseMatrixType>>();

	g2o::OptimizationAlgorithmLevenberg* solver = new g2o::OptimizationAlgorithmLevenberg(
		g2o::make_unique<g2o::BlockSolver_6_3>(std::move(linearSolver)));
```
As above. This compiles, but is this correct?

Thanks again!

**Comment by antithing** [comment]
Thank you! i have changed to:

```
	g2o::OptimizationAlgorithmLevenberg solver(g2o::OptimizationAlgorithmLevenberg(
		g2o::make_unique<g2o::BlockSolver_6_3>(std::move(linearSolver))));
	

    solver.setUserLambdaInit(1e-10);
    optimizer.setAlgorithm(&solver);
```

and it won't compile, giving me:

`'g2o::OptimizationAlgorithmLevenberg::OptimizationAlgorithmLevenberg(const g2o::OptimizationAlgorithmLevenberg &)': attempting to reference a deleted function`


Have i done this wrong?

**Comment by jumonatr** [comment]
Yes, here you're trying to build an OptimizationAlgorithmLevenberg object using another OptimizationAlgorithmLevenberg object.

Just do:

g2o::OptimizationAlgorithmLevenberg solver(g2o::make_unique<g2o::BlockSolver_6_3>(std::move(linearSolver)));

**Comment by antithing** [comment]
`g2o::OptimizationAlgorithmLevenberg solver(g2o::make_unique<g2o::BlockSolver_6_3>(std::move(linearSolver)));
`

compiles and runs great. Thank you again for your help.
