### ISSUE TITLE
Which coocrdinate system is used?

### ISSUE THREAD

**Issue by ronir121** [RainerKuemmerle/g2o#286]
Hi,
I was wondering which coordinate system is being used in g2o?
I'm ysing lsd-slam which uses g2o, and trying to understand which coordinate system is being used here. 
I thought it's x right, y up, z backward.
Am I correct?

**Comment by RainerKuemmerle** [comment]
g2o does not impose any specific coordinate system apart from a right handed one.
In principle, the error functions are based on relative measurements.

On July 11, 2018 9:27:52 AM GMT+02:00, ronir121 <notifications@github.com> wrote:
>Hi,
>I was wondering which coordinate system is being used in g2o?
>I'm ysing lsd-slam which uses g2o, and trying to understand which
>coordinate system is being used here. 
>I thought it's x right, y up, z backward.
>Am I correct?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/RainerKuemmerle/g2o/issues/286

-- 
Sent from a mobile device. Please excuse my brevity.

**Comment by ronir121** [comment]
When a camera is used in the SLAM optimization, there is an importance to determine the coordinate system that is being used.  Camera imposes re-projection constraints that their error is minimized in the system.
It is very important to know where the camera is looking to...
Can you help on this issue?
