### ISSUE TITLE
Memory Allocation

### ISSUE THREAD

**Issue by PizzocaroSolomon** [RainerKuemmerle/g2o#289]
good evening,
first of all, we thank you for the grate job done and shared !

using my project inside g2o folder and treating it like an Example (we have copied the CMakeLists  of tutorial_slam2d) all works fine.
If instead I install the libreries in "usr/local/...", and link them into my project, I get memory allocation problem in run-time. No problems compiling the project so I assume that it finds the necessary libreries and dependencies.

**Comment by sjulier** [comment]
What operating system? What errors?
