### ISSUE TITLE
g2o poor convergence: little noize added prevents reaching optimum

### ISSUE THREAD

**Issue by wf34** [RainerKuemmerle/g2o#302]
Hello,
the question isn't really a bug report but rather inquiry and plea for advice.
I believe, that a model I put together with g2o should converge better than it does. 
To put my issue plainly, it is:
- when I initialize model with ground truth data from simulated environment, it shows zero loss  
- when I initialize with slightly perturbed data, the optimization stops a little short of an optimal, zero loss solution

I do realize, that convexity of my problem is not established and that sub-optimal solution for non-convex problem is totally possible.
It can be the case that "winning" solution is totally unobservable from the data I provided in my simulation.
But I refuse to wave my hand on this problem like it's good enough, and am seeking a way to investigate this case of poor convergence.

I model 3D SLAM case, where there are two types of vertices and 3 types of edges:
Vertices:  
1. Agent body poses (SE3) in the world frame
2. Sensor's pose relative to the body frame (calibration vertex)
Edges:
1. Global positioning edges: measure Agent body poses in the world frame
2. Relative positioning edges: current agent body pose in the coordinate frame of a previous body pose
3. Sensor edges: slight modification of the `Edge_V_V_GICP` which only takes into account that ICP measurement is between sensors, not body poses

I put together minimal example, which turned out to be not so minimal, so I insert excerpts from it below and full code [here](https://gist.github.com/wf34/7cdd74e4790ed5a7923ab54f81a57bdc). 
```  
int main(int argc, char** argv) {
  assert (argc == 2);
  std::string mode(argv[1]);
  assert(mode == "ideal" || mode == "with_noize");
  data gt, measured;
  OptPtr o = get_optimizer();
  if ("ideal" == mode) {
    generator(CalibCases::ID, 0, &gt, &measured);
  } else if ("with_noize" == mode) {
    generator(CalibCases::SMALL_NOIZE, 1, &gt, &measured);
  }
  data gt, measured;
  OptPtr o = get_optimizer();
  generator(CalibCases::MEDIUM_NOIZE, 1, &gt, &measured);

  const size_t calib_edge_id = measured.global.size();
  auto calib_vert = new g2o::VertexSE3();
  calib_vert->setEstimate(measured.t_b_s);
  calib_vert->setId(calib_edge_id);
  o->addVertex(calib_vert);

  const CloudPtr bunny = load_bunny();
  std::vector<CloudPtr> local_clouds;
  for (size_t i = 0; i < measured.global.size(); ++i) {
    const Eigen::Isometry3d t_w_b(gt.global.at(i));
    const Eigen::Isometry3d mt_w_b(measured.global.at(i));
    const Eigen::Isometry3d t_w_s = t_w_b * gt.t_b_s;
    auto body_vert = new g2o::VertexSE3();
    body_vert->setEstimate(mt_w_b);
    body_vert->setId(i);
    o->addVertex(body_vert);

    auto global_edge = new SimpleGlobalEdge();
    global_edge->setVertex(0, body_vert);
    global_edge->setMeasurement(mt_w_b.translation());
    global_edge->setInformation(Eigen::Matrix3d::Identity());
    o->addEdge(global_edge);
    global_edge->computeError();
    printf("glo edge error: %.6f\n", global_edge->error().norm());
  }

  for (size_t i = 0; i < measured.relative.size(); ++i) {
    size_t source_id = (i + 1) % measured.relative.size();
    size_t dst_id = i;
    const auto source_vertex = get_vertex(o, source_id);
    const auto destination_vertex = get_vertex(o, dst_id);
    const Eigen::Isometry3d t_bi_bj(measured.relative.at(i));
    auto local_edge = new g2o::EdgeSE3();
    local_edge->setVertex(1, source_vertex);
    local_edge->setVertex(0, destination_vertex);
    local_edge->setMeasurement(t_bi_bj);
    local_edge->setInformation(Matrix6d::Identity());
    o->addEdge(local_edge);
    local_edge->computeError();
    printf("rel edge error: %.6f\n", local_edge->error().norm());

    double icp_error{0};
    for (size_t j = 0; j < bunny->size(); ++j) {
      auto graph_edge = new Edge_V_V_GICP_Calib();
      graph_edge->setVertex(1, source_vertex);
      graph_edge->setVertex(0, destination_vertex);
      graph_edge->setVertex(2, calib_vert);
      
      const auto& point_from_target = (*local_clouds.at(dst_id))[j];
      const auto& point_from_source = (*local_clouds.at(source_id))[j];
      g2o::EdgeGICP measurement;
      measurement.pos0 = point_from_target.getVector3fMap().cast<double>();
      measurement.pos1 = point_from_source.getVector3fMap().cast<double>();
      measurement.normal0 = point_from_target.getNormalVector3fMap().cast<double>();
      measurement.normal1 = point_from_source.getNormalVector3fMap().cast<double>();
      graph_edge->setMeasurement(measurement);
      graph_edge->setInformation(Eigen::Matrix3d::Identity());
      o->addEdge(graph_edge);
      graph_edge->computeError();
      icp_error += graph_edge->error().norm() / bunny->size();
    }
    printf("ICP edge error: %.6f\n", icp_error);
  }

  o->setVerbose(true);
  o->initializeOptimization();
  o->computeActiveErrors(); 
  printf("Vertices: %ld.  Active: %ld\n", o->vertices().size(), o->activeVertices().size());
  printf("Edges: %ld. Active: %ld\n", o->edges().size(), o->activeEdges().size());
  printf("Prior chi2: %f\n", o->activeChi2());
  o->optimize(50);
  printf("Resulting chi2: %f\n", o->activeChi2());
}
```  

This yields following output for the ideal, noizeless case: 
```
Prior chi2: 0.000000
Resulting chi2: 0.000000
```

But optimum is not achieved if we perturb the input a little bit: 
```
Prior chi2: 3.212850
Resulting chi2: 0.01533
```
I'm so reluctant to accept unobservability theory because agent's trajectory in this simulated environment is highly dynamic, with a lot of motion in all 6 degrees of freedom and all ICP correspondences initialized ideal in both ideal and noize cases.

Thank you for your replies. And amazing library!

**Comment by sjulier** [comment]
As identified, this sounds like a local minimum and is not an observability issue. Observability would be a chi2 of 0 and a non-zero error in your estimate. It doesn't sound like this is the case here.

Can you manually set the estimate on the nodes - e.g., by interpolating between the optimal and converged solutions, using setEstimate and then computing chi2(.) on the whole graph - to see the behaviour of the cost function? If your global minimum is ring fenced by a bunch of local maxima, then this is clearly a problem. Ideal point correspondence will not address this issue.

People I know who work in sensor alignment, calibration and photogrammetry typically run a set of optimisers with perturbed initial conditions and pick the best of them to try to avoid local minima. That might be your best bet here. (How long does it take to run?) A more theoretical approach is to use Bayesian optimisation, which tries to estimate what the cost surface and then picks points which maximise the probability of improving the best solution.
