### ISSUE TITLE
BA_demo not working if just fixing one frame

### ISSUE THREAD

**Issue by Bardo91** [RainerKuemmerle/g2o#305]
I am trying to run BA in my project but I experienced some issues that I am not sure to undersand. So at first I copied the ba_demo and added a piece of code for plotting the result.

The following picture shows the result of the example (as it is in the repo) with first two vertices fixed.
![image](https://user-images.githubusercontent.com/3602335/45932138-37ec1680-bf78-11e8-9de2-6051c6ed5b20.png)

And the next picture shows the result of the example if only fixing the first vertex (https://github.com/RainerKuemmerle/g2o/blob/c2f4eb8271d19476fa7934c485d2508f3277fbd3/g2o/examples/ba/ba_demo.cpp#L174). In this second picture, the points and poses (small coordinates are the init poses and bigger ones are the optimized) are shifted. Even if the optimizer said it converged (many steps of iteration with chi2 = 0).
![image](https://user-images.githubusercontent.com/3602335/45932118-10954980-bf78-11e8-98f8-1ccc85b4025d.png)

Does anyone experienced something similar? My concern is that I cannot set two first frames fix because if the second one might have noise. If I fix the second frame the noise propagates.

**Comment by RainerKuemmerle** [comment]
You need to provide the scale to the optimizer which is done by fixing two frames.

**Comment by Bardo91** [comment]
That makes a lot of sense. But, then, what confuses me is how is it used in the ORB_SLAM2 library (https://github.com/raulmur/ORB_SLAM2/blob/f2e6f51cdc8d067655d90a78c06261378e07e8f3/src/Optimizer.cc#L79) it seems to me that it is only fixing the first frame, so, how is possible that it works? Is it because the algorithm is close to the minimum?
