### ISSUE TITLE
cmake build error on macOS

### ISSUE THREAD

**Issue by zjzcn1** [RainerKuemmerle/g2o#321]
mac version: 10.14

error:
g2o/g2o/types/slam2d/edge_se2_pointxy_bearing.cpp:51:19: error: reference to type 'const Eigen::Rotation2Dd'
      (aka 'const Rotation2D<double>') could not bind to an rvalue of type 'double'
    t.setRotation(t.rotation().angle()+_measurement);

**Comment by Pablitinho** [comment]
I have seen this problem before, just apply a casting or use this function:
t.setRotation(Rotation2D(t.rotation().angle()+_measurement));
