### ISSUE TITLE
Cross Compile Android with Optimization

### ISSUE THREAD

**Issue by simonprovost** [RainerKuemmerle/g2o#323]
Hello,

Theses configurations will works with cross compile for Android ? 

> set(ANDROID_ABI "armeabi-v7a with neon")
> set(ANDROID_TOOLCHAIN clang)
> set(ANDROID_NATIVE_API_LEVEL 24)
> set(ANDROID_STL c++_static)

Thank you.

**Comment by cusoh** [comment]
Yes. It does work.
