### ISSUE TITLE
Cholesky failure

### ISSUE THREAD

**Issue by skasperski** [RainerKuemmerle/g2o#35]
Hallo,

I am using g2o to solve a laser based 2D-SLAM. I used the types from types/slam2d to build the graph and the Cholmod-LinearSolver for the optimization process. It seems to work correctly from time to time, but often the call to optimize() fails and I get:

> Cholesky failure, writing debug.txt (Hessian loadable by Octave)

on the console. What could be a reason / solution for this?

Best regards,
Sebastian

**Comment by lindzey** [comment]
For anybody encountering this later, I had a similar error that was due to setting the wrong node to fixed, such that my graph still had gauge freedom.

You can test and fix this with something like:
```cpp
bool has_gauge_freedom = optimizer->gaugeFreedom();
if (has_gauge_freedom) {
  g2o::OptimizableGraph::Vertex* gauge_node = optimizer->findGauge();
  gauge_node->setFixed(true);
}
```
