### ISSUE TITLE
Really need an official python bonding.

### ISSUE THREAD

**Issue by lvgeng** [RainerKuemmerle/g2o#361]
I know that there is a something.
https://github.com/uoip/g2opy

I noticed that there has been some bug fixing since the last year for g2o, but the g2opy and even the github account itself has been inactivated for quite a long time, and it seems to be impossible to add customized error function.

Is there any plan for a python bonding? Or... at least a updated version of g2opy?

**Comment by RainerKuemmerle** [comment]
In spare time I worked on better python support. In the meantime also allows some types implementation in python.
see https://github.com/RainerKuemmerle/g2o/issues/626
