### ISSUE TITLE
Data Association

### ISSUE THREAD

**Issue by jadhm** [RainerKuemmerle/g2o#375]
Hi,

I am tending to use g2o to solve an optimization problem. My problem consists of observed landmarks and odometry. This will  be used as input to the solver. The question is; does g2o solve the data association problem ? in case yes which algorithm is used ? 

Thanks in advance,
Regards

**Comment by RainerKuemmerle** [comment]
g2o is not implementing any data association algorithms.
It solves the optimization problem given a set of constraints in which data association is given.
