### ISSUE TITLE
edge setParameterId

### ISSUE THREAD

**Issue by MinaHenein** [RainerKuemmerle/g2o#379]
Hi there,
I'm new to g2o and I can't really understand the use of edge set parameter id, and I'm failing to find enough examples to understand this.

Basically for every landmark observation and the camera prior, I had to add a line:
edge->setParameterId(0, 0); otherwise it doesn't run, but I'm not sure what it actually means.

Thanks a lot

**Comment by YangSiri** [comment]
Hi, MinaHenein, do you have any thoughts about that ?

**Comment by MinaHenein** [comment]
Hi YangSiri, I think that for every landmark observation, setParameterId(cam_id) makes the system know that this observation happens from the camera with id = cam_id and I guess it is related to: 

g2o::ParameterSE3Offset* cameraOffset = new g2o::ParameterSE3Offset;
cameraOffset->setId(0);
optimizer.addParameter(cameraOffset); 

however these are all my thoughts/understandings, I can't confirm anything yet.

**Comment by YangSiri** [comment]
yes, i thought about that too, its all about the camera paras

**Comment by nickponline** [comment]
@MinaHenein @YangSiri  Did either of you get an answer? I'm have the same question .. :)

**Comment by MinaHenein** [comment]
I didn't get any answer, but I'm fairly confident my hypothesis is valid

**Comment by RainerKuemmerle** [comment]
Yes, it relates to the given ParameterSE3Offset for which you have to provide the ID.
