### ISSUE TITLE
In  computeEdgeSE3Gradient, why are the jacobians dependent on the error?

### ISSUE THREAD

**Issue by MinaHenein** [RainerKuemmerle/g2o#381]
In computeEdgeSE3Gradient, which computes the jacobians of the edge_se3 function, why are the jacobians dependent on the error between the expected and measured values?

void computeEdgeSE3Gradient(Isometry3& E,
                              Eigen::MatrixBase<Derived> const & JiConstRef, 
                              Eigen::MatrixBase<Derived> const & JjConstRef,
                              const Isometry3& Z, 
                              const Isometry3& Xi,
                              const Isometry3& Xj)
  {
    Eigen::MatrixBase<Derived>& Ji = const_cast<Eigen::MatrixBase<Derived>&>(JiConstRef);
    Eigen::MatrixBase<Derived>& Jj = const_cast<Eigen::MatrixBase<Derived>&>(JjConstRef);
    Ji.derived().resize(6,6);
    Jj.derived().resize(6,6);
    // compute the error at the linearization point
    const Isometry3 A=Z.inverse();
    const Isometry3 B=Xi.inverse()*Xj;

    E=A*B;

    Isometry3::ConstLinearPart Re = extractRotation(E);
    Isometry3::ConstLinearPart Ra = extractRotation(A);
    Isometry3::ConstLinearPart Rb = extractRotation(B);
    Isometry3::ConstTranslationPart tb = B.translation();  

    Eigen::Matrix<number_t, 3, 9, Eigen::ColMajor>  dq_dR;
    compute_dq_dR (dq_dR, 
        Re(0,0),Re(1,0),Re(2,0),
        Re(0,1),Re(1,1),Re(2,1),
        Re(0,2),Re(1,2),Re(2,2));

    Ji.setZero();
    Jj.setZero();

    // dte/dti
    Ji.template block<3,3>(0,0)=-Ra;

    // dte/dtj
    Jj.template block<3,3>(0,0)=Re;

    // dte/dqi
    {
      Matrix3 S;
      skewT(S,tb);
      Ji.template block<3,3>(0,3)=Ra*S;
    }

    // dte/dqj: this is zero

    number_t buf[27];
    Eigen::Map<Eigen::Matrix<number_t, 9, 3, Eigen::ColMajor> > M(buf);
    Matrix3 Sxt,Syt,Szt;
    // dre/dqi
    {
      skewT(Sxt,Syt,Szt,Rb);
      Eigen::Map<Matrix3> Mx(buf);    Mx.noalias() = Ra*Sxt;
      Eigen::Map<Matrix3> My(buf+9);  My.noalias() = Ra*Syt;
      Eigen::Map<Matrix3> Mz(buf+18); Mz.noalias() = Ra*Szt;
      Ji.template block<3,3>(3,3) = dq_dR * M;
    }

    // dre/dqj
    {
      Matrix3& Sx = Sxt;
      Matrix3& Sy = Syt;
      Matrix3& Sz = Szt;
      skew(Sx,Sy,Sz,Matrix3::Identity());
      Eigen::Map<Matrix3> Mx(buf);    Mx.noalias() = Re*Sx;
      Eigen::Map<Matrix3> My(buf+9);  My.noalias() = Re*Sy;
      Eigen::Map<Matrix3> Mz(buf+18); Mz.noalias() = Re*Sz;
      Jj.template block<3,3>(3,3) = dq_dR * M;
    }
  }

**Comment by RainerKuemmerle** [comment]
You'll typically see some relation between the error function and its Jacobian.
