### ISSUE TITLE
Understanding format of g2o file

### ISSUE THREAD

**Issue by hkhanr** [RainerKuemmerle/g2o#392]
Hi,
I want to create a g2o file of my own dataset and perform some optimization, however, I have been facing some issues in understanding the format of g2o file. I have the Key frames from ORB_Slam and the poses between the consecutive frames i.e Rotation (R) and Translation (T) as shown in following figure

![Untitled drawing](https://user-images.githubusercontent.com/47419730/68941975-204d9e00-07c9-11ea-9d2e-8c90699c7fd9.jpg)

In g2o file, first all the poses for respective keyframes are mentioned with "VERTEX_SE3" e.g. VERTEX_SE3:QUAT 1 0.341895 -0.0416997 0.0330394 -0.00189341 0.00395691 0.0899835 0.995934 where the first three values are x,y,z coordinates and others are quaternions).  After that, there is "EDGE_SE3" section in which I am facing problem to understand (e.g. EDGE_SE3:QUAT 0 1 0.341895 -0.0416997 0.0330394 -0.00189341 0.00395691 0.0899835 0.995934  10 0 0 0 0 0 10 0 0 0 0 10 0 0 0 400.021 0.00193512 2.06612 399.993 0.496977 99.203). In  "EDGE_SE3", I think the first two values show the link between frames. I don't understand the the succeeding values. What are these values in case of keyframes from ORB_Slam and how to calculate them? What is format of g2o file?

**Comment by zhkai929** [comment]
VERTEX_SE3:QUAT ID x y z q_x q_y q_z q_w
// where the quaternion is in Hamilton form.

EDGE_SE3:QUAT ID_a ID_b x_ab y_ab z_ab q_x_ab q_y_ab q_z_ab q_w_ab I_11 I_12 I_13 ... I_16 I_22 I_23 ... I_26 ... I_66 
// where I_ij is the (i, j)-th entry of the information matrix for the  measurement. Only the upper-triangular part is stored. The measurement order  is the delta position followed by the delta orientation.
