### ISSUE TITLE
g2o_viewer exit when press optimize button

### ISSUE THREAD

**Issue by SYSUHPK** [RainerKuemmerle/g2o#393]
Dear @RainerKuemmerle  and other contributers,
 I can run the following command:
<pre>
g2o_viewer xx.g2o
</pre>
and it can show me the picture, but when I press the **optimize** button, it will exit and tell me 
<pre>
Segment fault (core dumped) 
</pre>
A few other buttons still work.
What's the problem?

**Comment by RainerKuemmerle** [comment]
Please provide the data file.
