### ISSUE TITLE
Clang-Tidy causes error when using  g2o/core/factory.h   #define code part

### ISSUE THREAD

**Issue by cusoh** [RainerKuemmerle/g2o#394]
While trying to compile [a slam code](https://github.com/tum-vision/lsd_slam/blob/master/lsd_slam_core/src/GlobalMapping/g2oTypeSim3Sophus.cpp)  [line 30, 32, 34, 35] I am getting the following error 
`
g2oTypeSim3Sophus.cpp:0: error: undefined reference to 'g2o_type_group_sba'`

I'm stuck and cannot proceed with the build. Please help in resolving this error.

**Comment by RainerKuemmerle** [comment]
Are you linking to types_sba library? Please also consider to ask the authors of the respective SLAM code instead.
