### ISSUE TITLE
Nothing displayed in g2o_viewer on Ubuntu 18.04

### ISSUE THREAD

**Issue by hustchenli** [RainerKuemmerle/g2o#425]
I tried to visualize a g2o-file using g2o_viewer. But nothing displayed. There is no warning or error.
![g2o_viewer_err1](https://user-images.githubusercontent.com/54683737/85806913-ad3dda00-b750-11ea-9a4e-e9897caa1ae7.png)
![g2o_viewer_err2](https://user-images.githubusercontent.com/54683737/85806940-b9c23280-b750-11ea-93ef-06c3aedd3ab0.png)
The example that I used is from [here](https://github.com/gaoxiang12/slambook2/blob/master/ch10/sphere.g2o).
Is there anything missing? How can I use g2o_viewer to visualize g2o-files? Thanks for your attention.

**Comment by RainerKuemmerle** [comment]
Can you provide your g2o config.h? It's located inside your build directory. I would assume that g2o is compiled without visualization support.

**Comment by hustchenli** [comment]
@RainerKuemmerle Thanks for your comment. Here is the config.h inside build directory: 
![config](https://user-images.githubusercontent.com/54683737/85943773-83440d80-b932-11ea-80ef-48bbe26833e1.png)

**Comment by RainerKuemmerle** [comment]
Looking at your screenshot of the viewer, there seems to be something else not working.
Even if the types cannot be displayed by the viewer, we should see a coordinate frame.

The error about the constructor does not appear on my system (Ubuntu 20.04).
Which version of libqglviewer do you have?

**Comment by hustchenli** [comment]
> Looking at your screenshot of the viewer, there seems to be something else not working.
> Even if the types cannot be displayed by the viewer, we should see a coordinate frame.
> 
> The error about the constructor does not appear on my system (Ubuntu 20.04).
> Which version of libqglviewer do you have?

libQGLViewer-2.7.2 and my system is ubuntu 18.04
