### ISSUE TITLE
some puzzle about the init lambda of OptimizationAlgorithmLevenberg

### ISSUE THREAD

**Issue by varyshare** [RainerKuemmerle/g2o#428]
Hi, in Ceres the OptimizationAlgorithmLevenberg's initial lambda near 1e-4, and it seems works well.
In g2o, OptimizationAlgorithmLevenberg's initial lambda is too large. So I wonder why this is done? Are there any other considerations here?

**Comment by RainerKuemmerle** [comment]
I think, we used some algorithm that tries to initialize the initial lambda based on the problem to be solved.
If there is a better strategy that works smoothly in practical applications, I am happy to receive a PR or further hints on what should be changed.
Thanks.
