### ISSUE TITLE
qt conflict in Ubuntu 20.04 from a conda env

### ISSUE THREAD

**Issue by darthgera123** [RainerKuemmerle/g2o#446]
ubuntu 20.04
output of make is here - https://pastebin.com/9i7pDt2A
qmake version is ```QMake version 3.1 Using Qt version 5.9.7 in /home/gera/anaconda3/envs/mr_assignment1/lib```
Unable to install after installing all optional packages and running cmake successfully
Error that i am getting is 
```
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libQGLViewer-qt5.so: undefined reference to `qt_version_tag@Qt_5.12'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [g2o/apps/g2o_viewer/CMakeFiles/g2o_viewer.dir/build.make:101: ../bin/g2o_viewer] Error 1
make[1]: *** [CMakeFiles/Makefile2:1551: g2o/apps/g2o_viewer/CMakeFiles/g2o_viewer.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

```
Please help

**Comment by darthgera123** [comment]
@RainerKuemmerle @ericperko

**Comment by Shubodh** [comment]
We already spent some time discussing it [here](https://github.com/Shubodh/MR-project1-pgo/issues/5). You might want to take a look there for the config/what all we've looked at so far.

**Comment by RainerKuemmerle** [comment]
Your pasted qmake output is not matching Ubuntu 20.04.
```
$ qmake -v
QMake version 3.1
Using Qt version 5.12.8 in /usr/lib/x86_64-linux-gnu
```

I guess there is some mixture happening with picking up Qt from Anaconda and trying it to link with a system library that requires Qt 5.12.
I am not using that framework but on my plain Ubuntu 20.04 laptop I can build and link g2o_viewer.

In the linked discussion we can see with your setup
 ```
QGLVIEWER_LIBRARY_DEBUG          QGLVIEWER_LIBRARY_DEBUG-NOTFOUND                                                                                                                                                
 QGLVIEWER_LIBRARY_RELEASE        /usr/lib/x86_64-linux-gnu/libQGLViewer-qt5.so                                                                                                                                   
 Qt5Core_DIR                      /home/tanmay/anaconda3/lib/cmake/Qt5Core                                                                                                                                        
 Qt5Gui_DIR                       /home/tanmay/anaconda3/lib/cmake/Qt5Gui                                                                                                                                         
 Qt5OpenGL_DIR                    /home/tanmay/anaconda3/lib/cmake/Qt5OpenGL                                                                                                                                      
 Qt5Widgets_DIR                   /home/tanmay/anaconda3/lib/cmake/Qt5Widgets                                                                                                                                     
 Qt5Xml_DIR                       /home/tanmay/anaconda3/lib/cmake/Qt5Xml                                                                                                                                         
 Qt5_DIR                          /home/tanmay/anaconda3/lib/cmake/Qt5 
```
You get libqglviewer and qt from different sources which causes a mismatch.

Plain Ubuntu 20.04:
```
 QGLVIEWER_LIBRARY_RELEASE        /usr/lib/x86_64-linux-gnu/libQGLViewer-qt5.so                                                      
 Qt5Core_DIR                      /usr/lib/x86_64-linux-gnu/cmake/Qt5Core                                                            
 Qt5Gui_DIR                       /usr/lib/x86_64-linux-gnu/cmake/Qt5Gui                                                             
 Qt5OpenGL_DIR                    /usr/lib/x86_64-linux-gnu/cmake/Qt5OpenGL                                                          
 Qt5Widgets_DIR                   /usr/lib/x86_64-linux-gnu/cmake/Qt5Widgets                                                         
 Qt5Xml_DIR                       /usr/lib/x86_64-linux-gnu/cmake/Qt5Xml                                                             
 Qt5_DIR                          /usr/lib/x86_64-linux-gnu/cmake/Qt5
```
Here libQGLViewer matches the provided Qt version.

**Comment by Shubodh** [comment]
Thanks for the reply, @RainerKuemmerle . We could resolve the problem.

The reason for confusion was that in Ubuntu 18.04, the installation works fine for exactly the same CMake config as above (i.e. `Qt5Core_DIR` using conda's qt) (since both use qt 5.9 in 18.04). But 20.04 uses 5.12 whereas conda uses 5.9, hence there's a mismatch.

You could find more details in our discussion [here](https://github.com/Shubodh/MR-project1-pgo/issues/5#issuecomment-708898269). Basically forcing CMake to use system path (`/usr/lib/..`) instead of conda path will resolve the issue.

You could rename this issue to something like "qt conflict in 20.04 from a conda env" and resolve this issue.

**Comment by RainerKuemmerle** [comment]
Thanks for the feedback and nice that the problem got sorted out.

**Comment by busybeaver42** [comment]
Use cmake with:
PATH=$PATH_WITHOUT_CONDA cmake -DCMAKE_BUILD_TYPE=RELEASE ..
That solve for me the issue.

**Comment by wangzheqie** [comment]
这是来自QQ邮箱的自动回复邮件。你好，我已经收到你的邮件，尽快处理。
