### ISSUE TITLE
ECCN for g2o

### ISSUE THREAD

**Issue by akshayrb9** [RainerKuemmerle/g2o#450]
Hi, For documentation purpose and project release process we need the Export control classification number(ECCN) for g2o if it applies. Can you please let me know the ECCN ?

**Comment by RainerKuemmerle** [comment]
As already communicated in personal email there is no such number for g2o.

**Comment by akshayrb9** [comment]
Thanks RainerKuemmerle ! . My apologies I had forgot the earlier communication.
