### ISSUE TITLE
Understanding the difference between dimension(), estimateDimension() and minimalEstimateDimension()

### ISSUE THREAD

**Issue by sjulier** [RainerKuemmerle/g2o#476]
I'm currently writing some code to sample a g2o graph to provide information about the PDF implicitly encoded with it. The sampling will be implemented by calling the update() method with perturbations for each vertex, and the estimates from each vertex will be accumulated together into a single output vector.

Because I'd like it to work on pretty much any graph, I can't use the setEstimate() / estimate() methods on a vertex because these are defined by the template specialization of BaseVertex. Rather, I'm restricted to using the accessors available in the OptimizableGraph::Vertex.

For each vertex, there are potentially three different dimensions which can be returned together with two sets of setters and getters. These, together with my interpretation, are below:

- dimension(): This refers to the "low-level" dimension of the vertex which is used when building things like the sparse matrices internally. Specifically, when update() is called on a vertex, the array which is passed in has dimension() elements in it. dimension() is always set.
- estimateDimension(): This is the "high-level" number of dimensions needed for to represent the vertex state. The most obvious case is SE3 which uses 7 dimensions (3 position, 4 quaternion). The crucial point here is that it can contain redundancy. It's not clear to me, however, if the array which is passed in via setEstimateData is supposed to obey constraints (manifold?) or not. For example, in the SE3 case, is it always assumed that the last four elements must have a unit norm? I presume so, because of the Impl method. 
- minimalEstimateDimension(): This is the minimal dimension of the "high-level" state. For example, in SE3 it is 6 (3 position, 3 exponential map or similar). I assume that setting minimal data means the data will be transformed to the high level state representation through the custom Impl method. In the SE3 example, the exponential map would internally be converted to a quaternion. It's not clear to me if the input has to obey any constraints, such as the maximum value of the norm of the exponential map vector.

Although dimension() is guaranteed to be implemented, the estimateData / minimalEstimateData methods are not implemented - the default methods return a dimension of -1. All the g2o types appear to implement these methods though.

For most situations, when the methods are implemented

dimension() == estimateDimension() == minimalEstimateDimension()

Are these intrepretations correct?

Cheers,

Simon

**Comment by RainerKuemmerle** [comment]
The root of this implementation is the hierarchical optimization that was implemented in the scope of research quite some time ago. The methods are not in use in the core part of the library. I guess, that therefore, the method is not implemented for all types.
Your summary seems right to me, with the exceptions you already mentioned for the 3D pose case the dimensions should be equal most of the time. Actually, I think `dimension() == minimalEstimateDimension()` almost everywhere.
