### ISSUE TITLE
Usage of ceres in installed header files

### ISSUE THREAD

**Issue by skasperski** [RainerKuemmerle/g2o#477]
When using base_unary_edge, a build error is produced because EXTERNAL/ceres is not installed by g2o:

    /include/g2o/core/base_fixed_sized_edge.h:33:10: fatal error: EXTERNAL/ceres/fixed_array.h: No such file or directory
     #include "EXTERNAL/ceres/fixed_array.h"

So I guess Ceres should be installed or not used within installed header files.

**Comment by RainerKuemmerle** [comment]
I think I noticed that on the AD branch and added in this commit
https://github.com/RainerKuemmerle/g2o/pull/471/commits/d2272d0e20cac24b96bbb8de74632d8b8d58f99d

I'll cherry pick it into master.

**Comment by skasperski** [comment]
Still does not work. Ceres is installed to "g2o/EXTERNAL/ceres/...", but include-line is just "EXTERNAL/ceres/..."

**Comment by gregsensem** [comment]
same here! does rewind to a previous version help? thanks!

**Comment by RainerKuemmerle** [comment]
https://github.com/RainerKuemmerle/g2o/releases/tag/20201223_git should still be fine.
I now understood the issue. My bad.

**Comment by RainerKuemmerle** [comment]
Created a branch to tackle the issue. https://github.com/RainerKuemmerle/g2o/tree/move-external

**Comment by skasperski** [comment]
Now it seems to work for me. (with the move-external branch)

**Comment by RainerKuemmerle** [comment]
Thanks, I'll merge.
