### ISSUE TITLE
cs.h not installed

### ISSUE THREAD

**Issue by Dung-Han-Lee** [RainerKuemmerle/g2o#486]
Hello, I had the following issue. I checked issue #400 #182 #23 , but they all seem to at least had cs.h installed.

/usr/local/include/g2o/solvers/csparse/csparse_extension.h:27:10: fatal error: cs.h: No such file or directory
 #include <cs.h>

I clone from the master branch and build with:
 mkdir build && cd build && cmake .. && make -j8
 
however, cs.h was not installed. I was not able to find it under usr/local/include/g2o/EXTERNAL, or any elsewhere. Am I missing something during the installation process?

I am on ubuntu 18.04 and I have the following dependencies installed:
libsuitesparse-dev
qtdeclarative5-dev
qt5-qmake
libqglviewer-dev-qt5

**Comment by LiKangyuLKY** [comment]
hi, I have the same problem, how did you solve it？
