### ISSUE TITLE
Building g2o projects/examples on windows

### ISSUE THREAD

**Issue by aalbaali** [RainerKuemmerle/g2o#488]
Hello, 

I'm new to g2o and to C++ projects. I'm using Visual Studio 19 on a Windows platform. So far, I've been able to compile and build the entire g2o files; I have the g2o_*_d.dll generated. I also have the examples working and running (when I build them from within the g2o solution). 

However, when I try to extract the same examples (tutorial_slam2d) outside the directory, I struggle to get the project to work. I tried using the same CMakeLists.txt inside the examples, but there were missing links. So I tried manually adding the 'include' directory to the project, and then I **linked** the dynamic libraries g2o_core_d.dll, g2o_solver_eigen_d.dll, g2o_stuff_eigen_d.dll. 
But I get different errors. 

First, I got an error that M_PI is undefined (in simulator.cpp) for some reason. So I manually defined M_PI. Then when I fixed that, I got a linker error of undefined references. 

I need some help to build a simple example outside the g2o directory. Your help is much appreciated.

Thanks,

AA

**Comment by sjulier** [comment]
For missing M_PI, see:

https://stackoverflow.com/questions/6563810/m-pi-works-with-math-h-but-not-with-cmath-in-visual-studio

What errors do you get?
