### ISSUE TITLE
Memory release confusion

### ISSUE THREAD

**Issue by NERanger** [RainerKuemmerle/g2o#490]
In g2o/core/ownership.h

```cpp
namespace g2o
{
    template<typename T>
    void release(T* obj)
    {
        (void)obj;
#if G2O_DELETE_IMPLICITLY_OWNED_OBJECTS
        delete obj;
#endif
    }
}
```

I am confued by the template and `(void)obj` operation, it would be appreciated if anyone can explain what is done here to me.

**Comment by sjulier** [comment]
https://stackoverflow.com/questions/1486904/how-do-i-best-silence-a-warning-about-unused-variables
