### ISSUE TITLE
error ‘VertexSBAPointXYZ’ is not a member of ‘g2o’

### ISSUE THREAD

**Issue by Tengyun-Mo** [RainerKuemmerle/g2o#507]
I guess this is a problem about version of g2o. Does anyone know how to fix it ? I'm very appreciate it.

**Comment by banfandoujiao** [comment]
Its' name is VertexPointXYZ now

**Comment by lin123-stack** [comment]
> Can VertexPointXYZ be used as a drop-in replacement? That's what happened in the rest of the g2o code when the SBA vertex was removed. Otherwise, can you use a typedef?

this problem you solved right? I have the same problem,thanks

**Comment by lovelyyoshino** [comment]
OK,  I find that the VertexPointXYZ function is changed to VertexPointXYZ.

https://github.com/RainerKuemmerle/g2o/commit/0fcccb302787e70ff19f65e70fb103a1295b33a2

**Comment by RainerKuemmerle** [comment]
VertexPointXYZ has to be used instead.
