### ISSUE TITLE
problem using tutorial_slam2d with g2o_viewer

### ISSUE THREAD

**Issue by etrabes** [RainerKuemmerle/g2o#52]
Hi, i am new to g2o so i am trying to use the tutorial_slam2d as a starting point. when i try to load in g2o_viewer the tutorial_slam2d's output, namely the "tutorial_after.g2o" and "tutorial_before.g2o" i get errors like "unknown type TUTORIAL_VERTEX_SE2" "unknown type TUTORIAL_VERTEX_POINT_XY", etc.

reading answer of issue 45, i tryed to delete all of the "TUTORIAL_", but  still it doesnt work.
finally i change the .g2o like this:

TUTORIAL_VERTEX_POINT_XY replaced with VERTEX_XY
TUTORIAL_VERTEX_SE2 replaced with VERTEX_SE2
TUTORIAL_EDGE_SE2 replaced with EDGE_SE2
TUTORIAL_EDGE_SE2_POINT_XY replaced with EDGE_SE2_XY

this way it seems to load correctly, but it fails later (matrix not positive definite)

As i said, i am still trying to understand the framework, so i don't know if this is a problem with it or is something i am doing wrong.

thanks!

**Comment by HouBiaoLiu** [comment]
Then how to solve the display problem?
