### ISSUE TITLE
How to use unique_ptr for g2o

### ISSUE THREAD

**Issue by deeprun** [RainerKuemmerle/g2o#520]
Hi, I used to use the code below:

`
typedef` g2o::BlockSolver< g2o::BlockSolverTraits<6, 3> > Block;
Block::LinearSolverType* linearSolver = new g2o::LinearSolverCSparse<Block::PoseMatrixType>(); 
Block* solver_ptr = new Block(linearSolver); 
g2o::OptimizationAlgorithmLevenberg* solver = new g2o::OptimizationAlgorithmLevenberg(solver_ptr);
`

But this code does not compile with the new g2o code. How can I fix it?

**Comment by sjulier-overleaf** [comment]
Please check the examples in the repository. Some of them use factories to construct types, and others work directly without the use of the factories.

**Comment by whu-lyh** [comment]
checkout to a old version g2o, and this works.
