### ISSUE TITLE
cs.h no such file or directory

### ISSUE THREAD

**Issue by shahbhagyashree** [RainerKuemmerle/g2o#53]
I went through the issue mentioned here https://github.com/RainerKuemmerle/g2o/issues/23
But I am still facing the error even after making the suggested changes. I am downloading the g2o package from github as I have mentioned the link to download the package in my Makefile. I tried making the suggested changes to the files that are downloaded but I get the error again and again.

Any help on it will be appreciated.

Thanks

**Comment by sakurazhu** [comment]
![image](https://cloud.githubusercontent.com/assets/18479419/15824956/56443060-2c34-11e6-8c12-058ebcf67a9e.png)
i have met the same problem .when i tried to use @nitin5 your method , there is a new problem showed in the image .




sakura@ubuntu:~/g2o/g2o/build$ cmake ..
CMake Error: The current CMakeCache.txt directory /home/sakura/g2o/g2o/build/CMakeCache.txt is different than the directory /home/zero/code/g2o/g2o/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
CMake Error: The source "/home/sakura/g2o/g2o/CMakeLists.txt" does not match the source "/home/zero/code/g2o/g2o/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.

**Comment by nitin5** [comment]
Please install cmake-gui tool. Either it is not in path or bit installed.

Rgds

**Comment by sakurazhu** [comment]
![image](https://cloud.githubusercontent.com/assets/18479419/15844766/97efdb52-2c9f-11e6-9f60-057bcb63d89f.png)
![image](https://cloud.githubusercontent.com/assets/18479419/15844773/a9c2b0f2-2c9f-11e6-8caf-7926f5df0d74.png)
I used the absolute path to include the cs.h ,but why it shows that the directory is not exit?

**Comment by lastsongforu** [comment]
have anyone solved this problem finally? i got in trouble with it too... so annoying

**Comment by jinchenglee** [comment]
I'm new to Cmake. But I noticed that the error above occurs when you try to build from <top of tree>/g2o/examples/tutorial_slam2d/build dir. 

When you build from <top of tree>, the problems are gone and you will find the binary at <top of tree>/bin.

Hope this helps.

**Comment by cgbcgb** [comment]
@sakurazhu ,前几天遇到了同样的问题--“/usr/local/include/g2o/solvers/csparse/csparse_helper.h:23:16: fatal error: cs.h: No such file or directory”，安装g2o的过程基本是参照半闲居士（高博）的blog写的，今天终于解决了，所以Mark一下，解决过程如下：
问题的原因就是cs.h的路径没有添加到自己的工作空间下
1.将g2o安装文件中的cmake_modules文件夹，copy到自己写的子package的主目录下，而不是主工作空间下。in other words， 将cmake_modules文件夹copy到与添加g2o路径的CMakeLists.txt同目录下即可
2.一定要删除原工作目录的build和devel文件夹，重新执行catkin_make，然后找不到cs.h的问题就完美解决了

**Comment by Blackshaddock** [comment]
today，I have miss the same  issue。but i use the Qt Creator you can find cs.h in /usr/include/suitesparse, so you can add it in the include path, and then add /usr/lib/x86_64-linux-gnu/libcxsparse.so.3.1.2 in the lib.

**Comment by chenchen2015** [comment]
Had the same issue. Got it resolved by reinstalling `SuiteSparse` to `/usr/local`, which does not seems to be the default behavior. Here are the steps:

1. Checkout [SuiteSparse](https://github.com/jluttine/suitesparse) `git clone https://github.com/jluttine/suitesparse` or download from [their website](http://faculty.cse.tamu.edu/davis/suitesparse.html) and unzip.
2. Install to `/usr/local` with `sudo make install INSTALL=/usr/local`, append `-j4` to the end for example to run 4 jobs in parallel to accelerate as needed
3. Add the following cmake script to your `CMAKE_MODULE_PATH`
```cmake
# FindCSparse.cmake, put under /usr/share/cmake-{version}/Modules
# Look for csparse and set package handle args
FIND_PATH(CSPARSE_INCLUDE_DIR NAMES cs.h
  PATHS
  /usr/include/suitesparse
  /usr/include
  /opt/local/include
  /usr/local/include
  /sw/include
  /usr/include/ufsparse
  /opt/local/include/ufsparse
  /usr/local/include/ufsparse
  /sw/include/ufsparse
)

FIND_LIBRARY(CSPARSE_LIBRARY NAMES cxsparse
  PATHS
  /usr/lib
  /usr/local/lib
  /opt/local/lib
  /sw/lib
)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(
  CSPARSE DEFAULT_MSG
  CSPARSE_INCLUDE_DIR CSPARSE_LIBRARY
)
```
4. Add `find_package( CSparse REQUIRED )` to your `CMakeLists.txt` and you should have `CSPARSE_INCLUDE_DIR` and `CSPARSE_LIBRARY` available

**Comment by KyleHuo** [comment]
> @sakurazhu ,前几天遇到了同样的问题--“/usr/local/include/g2o/solvers/csparse/csparse_helper.h:23:16: fatal error: cs.h: No such file or directory”，安装g2o的过程基本是参照半闲居士（高博）的blog写的，今天终于解决了，所以Mark一下，解决过程如下：
> 问题的原因就是cs.h的路径没有添加到自己的工作空间下
> 1.将g2o安装文件中的cmake_modules文件夹，copy到自己写的子package的主目录下，而不是主工作空间下。in other words， 将cmake_modules文件夹copy到与添加g2o路径的CMakeLists.txt同目录下即可
> 2.一定要删除原工作目录的build和devel文件夹，重新执行catkin_make，然后找不到cs.h的问题就完美解决了

![2019-08-08 11-12-53屏幕截图](https://user-images.githubusercontent.com/50535916/62672540-b48bb600-b9cd-11e9-9a11-38d19fa38df0.png)
我按照你的说明，把cmake_modules放在我的程序文件夹里边，但仍然提示cs.h文件不存在。奇怪的是，我直接跑高博的g2o例程却没有报错，我用的是Kdevelop进行编译。

**Comment by Outlande** [comment]
> @sakurazhu ,前几天遇到了同样的问题--“/usr/local/include/g2o/solvers/csparse/csparse_helper.h:23:16: fatal error: cs.h: No such file or directory”，安装g2o的过程基本是参照半闲居士（高博）的blog写的，今天终于解决了，所以Mark一下，解决过程如下：
> 问题的原因就是cs.h的路径没有添加到自己的工作空间下
> 1.将g2o安装文件中的cmake_modules文件夹，copy到自己写的子package的主目录下，而不是主工作空间下。in other words， 将cmake_modules文件夹copy到与添加g2o路径的CMakeLists.txt同目录下即可
> 2.一定要删除原工作目录的build和devel文件夹，重新执行catkin_make，然后找不到cs.h的问题就完美解决了
