### ISSUE TITLE
g2o with fixed y position for ORB vehicle SLAM

### ISSUE THREAD

**Issue by deeprun** [RainerKuemmerle/g2o#531]
Hi, I am using images collected from a car to run ORB-SLAM2 (https://github.com/raulmur/ORB_SLAM2) which utilize g2o to optimize car position and map points. I found there was sever scale shift in the SLAM results from my monocular data. So I would like to add constraints to make it more stable. One thing I can do is to assume the car was driving on a flat surface so it had a fixed y position. Basically, from frame to frame, the y position of the car did not change. However, I do not know how to add this to the g2o code. Could anyone help? The original code using g2o is here https://github.com/raulmur/ORB_SLAM2/blob/master/src/Optimizer.cc.

**Comment by sjulier** [comment]
This issue has been posted to the ORB-SLAM issue list and I've sent a reply there. Could you close it here?
