### ISSUE TITLE
Cmake fails with MSVC12 due to CXX11 and CXX0X test failures.

### ISSUE THREAD

**Issue by dtmoodie** [RainerKuemmerle/g2o#54]
CMake output:

Performing Test COMPILER_SUPPORTS_CXX11
Performing Test COMPILER_SUPPORTS_CXX11 - Failed
Performing Test COMPILER_SUPPORTS_CXX0X
Performing Test COMPILER_SUPPORTS_CXX0X - Failed
CMake Error at CMakeLists.txt:223 (message):
  The compiler C:/Program Files (x86)/Microsoft Visual Studio
  12.0/VC/bin/x86_amd64/cl.exe has no C++11 support.  Please use a different
  C++ compiler.

Yet support for msvc is claimed.  Can I ignore this error?

**Comment by Sahloul** [comment]
I think you already fixed this issue after reverting the C++11 enforcement!
