### ISSUE TITLE
SLAM using g2o to optimiza pose, with problem: double free or corruption (out)

### ISSUE THREAD

**Issue by resplendent-star** [RainerKuemmerle/g2o#546]
Ubuntu18.04 C++14

here i will put a google drive link to upload the data and code,plz help me for it.
https://drive.google.com/file/d/1Ww1E_TPXplEJyNnIiLMk6wMUUGpheQef/view?usp=sharing

in the code , will occur problem in hw.cpp,after the g2o begin to optimiza pose

iteration= 0 chi2= 42.135095 time= 0.00112092 cumTime= 0.00112092 edges= 12 schur= 0 lambda= 0.308925 levenbergIter= 1

iteration= 1 chi2= 40.443812 time= 0.000368912 cumTime= 0.00148983 edges= 12 schur= 0 lambda= 0.102975 levenbergIter= 1

iteration= 2 chi2= 40.443603 time= 0.000330179 cumTime= 0.00182001 edges= 12 schur= 0 lambda= 0.068650 levenbergIter= 1

iteration= 3 chi2= 40.443603 time= 0.000329466 cumTime= 0.00214947 edges= 12 schur= 0 lambda= 0.045767 levenbergIter= 1

iteration= 4 chi2= 40.443603 time= 0.000329112 cumTime= 0.00247858 edges= 12 schur= 0 lambda= 0.030511 levenbergIter= 1

iteration= 5 chi2= 40.443603 time= 0.000335933 cumTime= 0.00281452 edges= 12 schur= 0 lambda= 0.020341 levenbergIter= 1

iteration= 6 chi2= 40.443603 time= 0.00307696 cumTime= 0.00589148 edges= 12 schur= 0 lambda= 732853400701821.500000 levenbergIter= 10

double free or corruption (out)

**Comment by resplendent-star** [comment]
> 请提供对您问题的最小工作示例的轻松访问 - 目前，访问需要登录且未公开共享。

sorry,I change the permission,now it is open access,without  the data, you could reproduce this error;thanks for you reply

**Comment by RainerKuemmerle** [comment]
i will close this. Sorry, the file is 192MB big and contains multiple programs.
Please help also the people that in their spare time would debug your issue by providing an access to a minimal working example.
https://en.wikipedia.org/wiki/Minimal_working_example
In your case, I would expect a single cpp file demonstrating the issue.
