### ISSUE TITLE
installing g20 have error "c++: internal compiler error: Segmentation fault (program cc1plus)"

### ISSUE THREAD

**Issue by AnthonyZby** [RainerKuemmerle/g2o#548]
Hello, I am trying to install g2o on turtlebot3, the system is: ubuntu18.04, Eigen: 3.2.10, g++ version :7.5.0.
but after I execute the "make" command, an error appears:
......
[ 67%] Linking CXX executable ../../../../bin/convertSegmentLine
[ 67%] Built target convertSegmentLine_application
[ 67%] Building CXX object g2o/apps/g2o_simulator/CMakeFiles/g2o_anonymize_observations_application.dir/g2o_anonymize_observations.cpp.o
[ 67%] Linking CXX executable ../../../../bin/g2o_anonymize_observations
[ 67%] Built target g2o_anonymize_observations_application
[ 68%] Building CXX object g2o/types/data/CMakeFiles/types_data.dir/types_data.cpp.o
[ 68%] Building CXX object g2o/types/data/CMakeFiles/types_data.dir/robot_data.cpp.o
[ 68%] Building CXX object g2o/types/data/CMakeFiles/types_data.dir/vertex_tag.cpp.o
[ 69%] Building CXX object g2o/types/data/CMakeFiles/types_data.dir/vertex_ellipse.cpp.o
[ 69%] Building CXX object g2o/types/data/CMakeFiles/types_data.dir/laser_parameters.cpp.o
[ 69%] Building CXX object g2o/types/data/CMakeFiles/types_data.dir/raw_laser.cpp.o
[ 70%] Building CXX object g2o/types/data/CMakeFiles/types_data.dir/robot_laser.cpp.o
[ 70%] Building CXX object g2o/types/data/CMakeFiles/types_data.dir/data_queue.cpp.o
[ 70%] Linking CXX shared library ../../../../lib/libg2o_types_data.so
[ 70%] Built target types_data
[ 70%] Building CXX object g2o/types/slam3d/CMakeFiles/test_isometry3d_mappings.dir/test_isometry3d_mappings.cpp.o
[ 71%] Linking CXX executable ../../../../bin/test_isometry3d_mappings
[ 71%] Built target test_isometry3d_mappings
[ 72%] Building CXX object g2o/types/slam3d/CMakeFiles/test_mat2quat_jacobian.dir/test_mat2quat_jacobian.cpp.o
[ 72%] Linking CXX executable ../../../../bin/test_mat2quat_jacobian
[ 72%] Built target test_mat2quat_jacobian
[ 72%] Building CXX object g2o/types/slam3d/CMakeFiles/test_slam3d_jacobian.dir/test_slam3d_jacobian.cpp.o
[ 73%] Linking CXX executable ../../../../bin/test_slam3d_jacobian
[ 73%] Built target test_slam3d_jacobian
[ 74%] Building CXX object g2o/types/sba/CMakeFiles/types_sba.dir/types_sba.cpp.o
c++: internal compiler error: Segmentation fault (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
g2o/types/sba/CMakeFiles/types_sba.dir/build.make:62: recipe for target 'g2o/types/sba/CMakeFiles/types_sba.dir/types_sba.cpp.o' failed
make[2]: *** [g2o/types/sba/CMakeFiles/types_sba.dir/types_sba.cpp.o] Error 4
CMakeFiles/Makefile2:1216: recipe for target 'g2o/types/sba/CMakeFiles/types_sba.dir/all' failed
make[1]: *** [g2o/types/sba/CMakeFiles/types_sba.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by RainerKuemmerle** [comment]
If you do not need those types consider consider disabling them.
No option to upgrade to Ubuntu 20.04?
