### ISSUE TITLE
There is an error in edge_se2.cpp

### ISSUE THREAD

**Issue by wjiangping** [RainerKuemmerle/g2o#550]
```C++
void EdgeSE2::linearizeOplus()
  {
    const VertexSE2* vi = static_cast<const VertexSE2*>(_vertices[0]);
    const VertexSE2* vj = static_cast<const VertexSE2*>(_vertices[1]);
    number_t thetai = vi->estimate().rotation().angle();

    Vector2 dt = vj->estimate().translation() - vi->estimate().translation();
    number_t si=std::sin(thetai), ci=std::cos(thetai);

    _jacobianOplusXi <<
        -ci, -si, -si*dt.x()+ci*dt.y(),
         si, -ci, -ci*dt.x()-si*dt.y(),
         0,  0,   -1;

    _jacobianOplusXj <<
         ci, si, 0,
        -si, ci, 0,
         0,  0,  1;

    const SE2& rmean = _inverseMeasurement;
    Matrix3 z;
    z.block<2, 2>(0, 0) = rmean.rotation().toRotationMatrix();
    z.col(2) << cst(0.), cst(0.), cst(1.);
    z.row(2).head<2>() << cst(0.), cst(0.);
    _jacobianOplusXi = z * _jacobianOplusXi;
    _jacobianOplusXj = z * _jacobianOplusXj;
  }
```
I think there is an error in the ```z.col(2) << cst(0.), cst(0.), cst(1.);```, it should be replaced by
```C++
double tx = rmean.translation().x();
double ty = rmean.translation().y();
z.col(2) << cst(tx), cst(ty), cst(1.);
```
In my project, the former impl will produce some strange result, after the modification, the result becoms OK.
I hope this will help the other users.

**Comment by RainerKuemmerle** [comment]
Can you post a minimal example where the existing implementation is wrong?
Note that we have implemented a unit test which compares the analytic Jacobian to a numerically obtained one: https://github.com/RainerKuemmerle/g2o/blob/master/unit_test/slam2d/jacobians_slam2d.cpp

**Comment by fhill122** [comment]
I verified that there is no err for the jacobian:
![IMG_20240429_180112](https://github.com/RainerKuemmerle/g2o/assets/13213165/7d974281-fd87-42b0-bf44-1b3a4182fa52)
same as EdgeSE2::linearizeOplus implementation
