### ISSUE TITLE
No autoformat config

### ISSUE THREAD

**Issue by Lishen1** [RainerKuemmerle/g2o#554]
It would be good to have .clang-format here to keep the coding style and generate less useless commit diffs.

**Comment by RainerKuemmerle** [comment]
Agree. The point is that a good share of the code base is more than 10 years old and so far only manually formatted.
We can add a config and apply it when refactoring code.

**Comment by Lishen1** [comment]
I suggest adding and applying auto-formatting once on the whole repository and making a commit. Don't mix code changing and reformatting simultaneously
