### ISSUE TITLE
c++: error: unrcognized command line option '-msse2'

### ISSUE THREAD

**Issue by felrock** [RainerKuemmerle/g2o#561]
When i build [g2o](https://github.com/RainerKuemmerle/g2o/releases/tag/20201223_git) during a docker build(QEMU) i get the following error:

```
[  0%] Building CXX object EXTERNAL/freeglut/CMakeFiles/freeglut_minimal.dir/freeglut_font.cpp.o
c++: error: unrecognized command line option ‘-msse2’
c++: error: unrecognized command line option ‘-msse3’
c++: error: unrecognized command line option ‘-mssse3’
c++: error: unrecognized command line option ‘-msse4.1’
c++: error: unrecognized command line option ‘-msse4.2’
```
I'm building for arm on a x86 machine and the error comes from DEFINE_SSE_VAR reading from /proc/cpuinfo which is the docker build host info, so msse2 etc is added anyway. This issue seems to be fixed by _check_cxx_compiler_flag_ on master branch. Is it possible to update the release with this aswell?

**Comment by RainerKuemmerle** [comment]
Does master work for you?
