### ISSUE TITLE
Assosiation problem

### ISSUE THREAD

**Issue by blauenase** [RainerKuemmerle/g2o#589]
I have a general question regarding the usage of this library. I´m using it for 2D SLAM with landmarks.

Whenever the system detects that a landmark was already added to the optimizer, it creates a new edge from the current pose to the landmark. While creating this edge I include the new measurement data (relative position of the landmark to the actor) and retrieve the associated landmark from the optimizer to connect to the pose. Is this the correct approach to create association in the pose-graph?
In my last approach I added a new PointXY Vertex for every landmark detection and this seems to be wrong.

**Comment by RainerKuemmerle** [comment]
Yes. Data association, i.e. which observation/measurement belongs to which
vertex of the graph has to be done by the front end.
This means what you do is correct. Whenever you identify a landmark as
already been seen before, you retrieve it from the graph and connect new
edges to it.

blauenase ***@***.***> schrieb am So., 22. Mai 2022, 01:44:
