### ISSUE TITLE
“setMarginalized(false)” lead to example "ba_demo.cc" error !

### ISSUE THREAD

**Issue by chennuo0125-HIT** [RainerKuemmerle/g2o#591]
I tested ba_demo.cc in g2o/examples/ba/ba_demo.cc directly, i get correct result, but when I modify “setMarginalized(true)” to “setMarginalized(false)”, i get following warning, how can i solve it ? 
![g2o_ba](https://user-images.githubusercontent.com/37269147/175758452-c645c9cd-df7e-4c0e-becc-2fd1efedae8f.png)

**Comment by RainerKuemmerle** [comment]
You also need to change the solver to accept different sizes of blocks. This seems to be a bug that solving is not rejected.

Diff would be something like
```
--- a/g2o/examples/ba/ba_demo.cpp
+++ b/g2o/examples/ba/ba_demo.cpp
@@ -113,7 +113,7 @@ int main(int argc, const char* argv[]) {
     solverName = "lm_dense6_3";
   } else {
 #ifdef G2O_HAVE_CHOLMOD
-    solverName = "lm_fix6_3_cholmod";
+    solverName = "lm_var_cholmod";
 #else
     solverName = "lm_fix6_3";
 #endif
@@ -171,7 +171,7 @@ int main(int argc, const char* argv[]) {
   for (size_t i = 0; i < true_points.size(); ++i) {
     auto v_p = std::make_shared<g2o::VertexPointXYZ>();
     v_p->setId(point_id);
-    v_p->setMarginalized(true);
+    v_p->setMarginalized(false);
     v_p->setEstimate(true_points.at(i) +

```

**Comment by chennuo0125-HIT** [comment]
@RainerKuemmerle thanks for you reply :) :) :)
