### ISSUE TITLE
 Compilation in aislib failed!!!

### ISSUE THREAD

**Issue by guojia19890817** [RainerKuemmerle/g2o#60]
hogman2d.cpp:(.text+0x1104): undefined reference to `cs_sfree'
hogman2d.cpp:(.text+0x14ed): undefined reference to `AISNavigation::Graph::vertex(int)'
hogman2d.o: In function `AISNavigation::ActivePathUniformCostFunction<AISNavigation::PoseGraph2D>::operator()(AISNavigation::Graph::Edge*, AISNavigation::Graph::Vertex*, AISNavigation::Graph::Vertex*)':
hogman2d.cpp:(.text._ZN13AISNavigation29ActivePathUniformCostFunctionINS_11PoseGraph2DEEclEPNS_5Graph4EdgeEPNS3_6VertexES7_[AISNavigation::ActivePathUniformCostFunction<AISNavigation::PoseGraph2D>::operator()(AISNavigation::Graph::Edge*, AISNavigation::Graph::Vertex*, AISNavigation::Graph::Vertex*)]+0x18): undefined reference to `typeinfo for AISNavigation::Graph::Edge'
hogman2d.o: In function `AISNavigation::PoseGraph<_Transformation<_Angle<double> >, _Matrix<3, 3, double> >::PathLengthCostFunction::operator()(AISNavigation::Graph::Edge*, AISNavigation::Graph::Vertex*, AISNavigation::Graph::Vertex*)':
hogman2d.cpp:(.text._ZN13AISNavigation9PoseGraphI15_TransformationI6_AngleIdEE7_MatrixILi3ELi3EdEE22PathLengthCostFunctionclEPNS_5Graph4EdgeEPNS9_6VertexESD_[AISNavigation::PoseGraph<_Transformation<_Angle<double> >, _Matrix<3, 3, double> >::PathLengthCostFunction::operator()(AISNavigation::Graph::Edge*, AISNavigation::Graph::Vertex*, AISNavigation::Graph::Vertex*)]+0x18): undefined reference to `typeinfo for AISNavigation::Graph::Edge'

**Comment by RainerKuemmerle** [comment]
Hello,

I saw your mail you sent to me yesterday. I can also see that the exclamation mark is working on your keyboard. But guess what, this is the issue tracker for g2o and not for hogman. Hence, this is totally the wrong place to report an issue with hogman.
Furthermore, please keep in mind that all of the source code is offered "as is" and I try to maintain it in my spare time. Thanks.

Best,
Rainer
