### ISSUE TITLE
Abstraction problem with BaseFixedSizedEdge

### ISSUE THREAD

**Issue by Lishen1** [RainerKuemmerle/g2o#611]
BaseFixedSizedEdge implement virtual Optimizable Graph::Vertex* create Vertex(int i) regardless what's vertex type are. createVertex(int i) force user to make Vertex Types by default constructable (what's not necessarily). For example I keep my types not default constructable to minimize problems with memory allocations, relocations and so on, and potentially it's suitable for g2o.

I suggest naive solution that at least allows code be compilable:
```
template <std::size_t I, typename... Tp>
typename std::enable_if<I >= sizeof...(Tp), OptimizableGraph::Vertex*>::type createNthVertexType(size_t) {
  return nullptr;  // end of recursion, return null
}
template <std::size_t I, typename... Tp>
typename std::enable_if <I < sizeof...(Tp), OptimizableGraph::Vertex*>::type createNthVertexType(size_t i) {
  if (i == I) {
    using VertexType = typename std::tuple_element<I, std::tuple<Tp...>>::type;
    if constexpr (std::is_default_constructible<VertexType>::value)
      return new VertexType();
    else
      return nullptr;
  } else
    return createNthVertexType<I + 1, Tp...>(i);
}
```
PS: if constexpr here just for example. can be solved by  std::enable_if sure.

**Comment by RainerKuemmerle** [comment]
We can also support passing arguments to constructors, see referenced commit.
