### ISSUE TITLE
HyperGraph DataContainer and Data double free

### ISSUE THREAD

**Issue by christiankerl** [RainerKuemmerle/g2o#62]
the destructor of HyperGraph::DataContainer deletes the whole chain of HyperGraph::Data objects. However, the destructor of HyperGraph::Data also tries to delete the next element in the object chain. Therefore, delete is called twice on some HyperGraph::Data objects. This is not an issue if there is only one HyperGraph::Data object in the container (I guess that is the reason why it was not reported earlier). The correct fix would be to change the HyperGraph::Data destructor to noop?!

DataContainer destructor: 
https://github.com/RainerKuemmerle/g2o/blob/master/g2o/core/hyper_graph.h#L124
Data destructor: 
https://github.com/RainerKuemmerle/g2o/blob/master/g2o/core/hyper_graph.cpp#L39

**Comment by RainerKuemmerle** [comment]
I guess the destructor of DataContainer should only delete _userData without running into the list.
