### ISSUE TITLE
g2o uses in active slam

### ISSUE THREAD

**Issue by nitin5** [RainerKuemmerle/g2o#63]
Greetings,
I have been successfully using g2o for optimization purpose, but mostly for batch optimization. I am implementing a active slam algorithm where i need marginalised covariances of each vertex to make a decision whether to go to new area or visit old node. Currently even after running optimization, i am getting empty marginalized matrices.
Is there any class which provide an example of how to do so? or any where i can look at?

Rgds
Nitin

**Comment by RainerKuemmerle** [comment]
What do you mean by empty marginalized matrices?
Please try to provide an example which allows us to reproduce the error.
