### ISSUE TITLE
SparseOptimizer::setAlgorithm does not free the old argorithm

### ISSUE THREAD

**Issue by TimPushkin** [RainerKuemmerle/g2o#631]
It seems to me that [SparseOptimizer::setAlgorithm](https://github.com/RainerKuemmerle/g2o/blob/5212e0a2c6c12c3db449e570632aa36f08966b8b/g2o/core/sparse_optimizer.cpp#L562) does not free the formerly used `OptimizationAlgorithm` that might have been set before. It just does `_algorithm = algorithm`. Shouldn't this cause a memory leak? And why isn't `OptimizationAlgorithm` managed through a `unique_ptr`?

**Comment by RainerKuemmerle** [comment]
Yes, seems like this could leak.
A large fraction of g2o was written when smart pointers have not been in the standard template library and requiring boost (or similar) was making things complicate on other platforms.

The pymem branch breaks API to use smart pointers. Here with keeping the API we could delete old pointer or manage with a unique_ptr instead. Some time ago, some parts migrated to smart pointers on master, but this caused lots of trouble for people to adapt code accordingly.
