### ISSUE TITLE
Is the newest release 20230223_git, or 20230226_git?

### ISSUE THREAD

**Issue by ZhongRuoyu** [RainerKuemmerle/g2o#639]
Hi, Homebrew maintainer here. While packaging the newest g2o release, we found that the [release](https://github.com/RainerKuemmerle/g2o/releases/tag/20230223_git) (`20230226_git`) was named differently from the tag (`20230223_git`). So, we wonder which one is the correct version. Thanks!

**Comment by RainerKuemmerle** [comment]
Hi, thanks for reporting. I renamed the release to match the tag. I had a typo when creating the tag and wanted to use today's date instead.

**Comment by ZhongRuoyu** [comment]
Noted. Thanks for confirming so swiftly, @RainerKuemmerle.
