### ISSUE TITLE
while compiling with cmake on ubuntu 20.04,  g2o_viewer failed after the 'make' command

### ISSUE THREAD

**Issue by ligang305** [RainerKuemmerle/g2o#647]
![2023-03-07_11-29](https://user-images.githubusercontent.com/3364082/223313387-3d6cf82b-5239-46a6-877a-e94cdf1871f5.png)

**Comment by RainerKuemmerle** [comment]
What's your cmake cache. Make sure the library for qglviewer is found and still in your cmake.
Built by calling make VEROSE=1 to see the linker command line.

**Comment by ligang305** [comment]
Thx, I have changed to the following branch and there is no error.
![2023-03-09_10-06](https://user-images.githubusercontent.com/3364082/223897300-fa35b080-6924-48b3-8dd6-ffd121ff4ce4.png)

**Comment by RainerKuemmerle** [comment]
I am a bit puzzled how that solved the problem.
Please re-open in case you want to follow up to understand the root-cause of the problem. Thanks.
