### ISSUE TITLE
eigen vector argument passing

### ISSUE THREAD

**Issue by Lishen1** [RainerKuemmerle/g2o#65]
MSVC compiling error
Error	37	error C2719: 'v': formal parameter with __declspec(align('16')) won't be aligned	c:\user_data\vc_projects\g2o-master\g2o\types\slam3d_addons\line3d.h	67

use oplus(const Vector6d& v) instead of oplus(Vector6d v) in all similar situation

**Comment by RainerKuemmerle** [comment]
Thanks. Would you mind posting a list of "all similar situations" that MSVC found?

**Comment by Lishen1** [comment]
Ok. yet I met only one such error.
