### ISSUE TITLE
How to disable cholmod logs?

### ISSUE THREAD

**Issue by goktugyildirim4d** [RainerKuemmerle/g2o#675]
How to disable cholmod logs like:` # Using CHOLMOD poseDim -1 landMarkDim -1 blockordering 1` ?

**Comment by RainerKuemmerle** [comment]
Unfortunately this is currently not easily possible because g2o internally directly writes into std::cerr for logging.
I was planning to integrate a logging library instead.
This would probably solve this issue.

**Comment by RainerKuemmerle** [comment]
Just as add-on. If you use the library in code, you can create the solver yourself instead of using the factory.

**Comment by RainerKuemmerle** [comment]
Merged the logger implementation to master. Such that you should be able to control which output will be generated to stdout. The mentioned logline is in the DEBUG level.
