### ISSUE TITLE
"spdlog::spdlog" target missing when including g2o in another cmake project

### ISSUE THREAD

**Issue by matlabbe** [RainerKuemmerle/g2o#682]
See https://github.com/introlab/rtabmap/issues/1031

It seems that this pull request https://github.com/RainerKuemmerle/g2o/pull/678 added spdlog logging ON by default. As the included target is public: 
```cmake
if (G2O_HAVE_LOGGING)
  if(TARGET spdlog::spdlog)
    target_link_libraries(stuff PUBLIC spdlog::spdlog)
  else()
    target_link_libraries(stuff PUBLIC spdlog::spdlog_header_only)
  endif()
endif()
```

The https://github.com/RainerKuemmerle/g2o/blob/master/cmake_modules/Config.cmake.in could have 
```cmake
if(@G2O_HAVE_LOGGING@)
  find_dependency(spdlog)
endif()
```
to let downstream packages including spdlog target.

**Comment by RainerKuemmerle** [comment]
Thanks. I added a commit with your suggested fix.

**Comment by matlabbe** [comment]
Great! thx
