### ISSUE TITLE
G2O_SINGLE_PRECISION_MATH error compilation

### ISSUE THREAD

**Issue by dimitryn** [RainerKuemmerle/g2o#702]
Hi , I am trying to compile origin/debian/humble/jammy/libg2o branch with G2O_SINGLE_PRECISION_MATH definition
I am getting errors 

     20%] Linking CXX shared library /home/administrator/Downloads/packages/libg2o-release/lib/libg2o_interface.so
cd /home/administrator/Downloads/packages/libg2o-release/build/g2o/examples/interactive_slam/slam_parser/interface && /home/administrator/Downloads/cmake-3.26.2-linux-x86_64/bin/cmake -E cmake_link_script CMakeFiles/interface_library.dir/link.txt --verbose=1
/home/administrator/Downloads/packages/libg2o-release/g2o/solvers/csparse/csparse_helper.cpp: In function ‘bool g2o::csparse_extension::writeCs2Octave(const char*, const cs_di*, bool)’:
/home/administrator/Downloads/packages/libg2o-release/g2o/solvers/csparse/csparse_helper.cpp:43:29: error: cannot convert ‘double* const’ to ‘const number_t*’ {aka ‘const float*’} in initialization
   43 |     const number_t* Ax = A->x;
      |                          ~~~^
      |                             |
      |                             double* const
/home/administrator/Downloads/packages/libg2o-release/g2o/solvers/csparse/csparse_helper.cpp:44:57: error: cannot convert ‘const number_t*’ {aka ‘const float*’} to ‘const double*’
   44 |     return writeCCSMatrix(filename, rows, cols, Ap, Ai, Ax, upperTriangular);
      |                                                         ^~
      |                                                         |
      |                                                         const number_t* {aka const float*}
In file included from /home/administrator/Downloads/packages/libg2o-release/g2o/solvers/csparse/csparse_helper.cpp:29:
/home/administrator/Downloads/packages/libg2o-release/g2o/stuff/sparse_helper.h:59:49: note:   initializing argument 6 of ‘bool g2o::writeCCSMatrix(const string&, int, int, const int*, const int*, const double*, bool)’
   59 |                                   const double* v,
      |                                   ~~~~~~~~~~~~~~^
/home/administrator/Downloads/packages/libg2o-release/g2o/solvers/csparse/csparse_helper.cpp:48:29: error: cannot convert ‘double* const’ to ‘const number_t*’ {aka ‘const float*’} in initialization
   48 |     const number_t* Ax = A->x;
      |                          ~~~^
      |                             |
      |                             double* const
/home/administrator/Downloads/packages/libg2o-release/g2o/solvers/csparse/csparse_helper.cpp:49:68: error: cannot convert ‘const number_t*’ {aka ‘const float*’} to ‘const double*’
   49 |     return writeTripletMatrix(filename, A->nz, rows, cols, Ai, Aj, Ax,
      |                                                                    ^~
      |                                                                    |
      |                                                                    const number_t* {aka const float*}
In file included from /home/administrator/Downloads/packages/libg2o-release/g2o/solvers/csparse/csparse_helper.cpp:29:
/home/administrator/Downloads/packages/libg2o-release/g2o/stuff/sparse_helper.h:74:68: note:   initializing argument 7 of ‘bool g2o::writeTripletMatrix(const string&, int, int, int, const int*, const int*, const double*, bool)’
   74 |                                       const int* Aj, const double* Ax,
      |                                                      ~~~~~~~~~~~~~~^~
/usr/bin/c++ -fPIC   -Wall -W -O3 -DNDEBUG -O3 -shared -Wl,-soname,libg2o_interface.so -o /home/administrator/Downloads/packages/libg2o-release/lib/libg2o_interface.so CMakeFiles/interface_library.dir/parser_interface.cpp.o CMakeFiles/interface_library.dir/slam_context_interface.cpp.o  -Wl,-rpath,/home/administrator/Downloads/packages/libg2o-release/lib: /home/administrator/Downloads/packages/libg2o-release/lib/libg2o_parser.so 
make[2]: *** [g2o/solvers/csparse/CMakeFiles/csparse_extension.dir/build.make:76: g2o/solvers/csparse/CMakeFiles/csparse_extension.dir/csparse_helper.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/administrator/Downloads/packages/libg2o-release/g2o/solvers/csparse/csparse_extension.cpp: In function ‘int g2o::csparse_extension::cs_cholsolsymb(const cs_di*, number_t*, const cs_dis*, number_t*, int*)’:
/home/administrator/Downloads/packages/libg2o-release/g2o/solvers/csparse/csparse_extension.cpp:54:23: error: cannot convert ‘number_t*’ {aka ‘float*’} to ‘const double*’
   54 |     cs_ipvec(S->pinv, b, x, n); /* x = P*b */
      |                       ^
      |                       |
      |                       number_t* {aka float*}
In file included from /home/administrator/Downloads/packages/libg2o-release/g2o/solvers/csparse/csparse_extension.h:27,
                 from /home/administrator/Downloads/packages/libg2o-release/g2o/solvers/csparse/csparse_extension.cpp:21:
/usr/include/suitesparse/cs.h:136:46: note:   initializing argument 2 of ‘int cs_di_ipvec(const int*, const double*, double*, int)’
  136 | int cs_di_ipvec (const int *p, const double *b, double *x, int n) ;
      |                                ~~~~~~~~~~~~~~^
/home/administrator/Downloads/packages/libg2o-release/g2o/solvers/csparse/csparse_extension.cpp:55:21: error: cannot convert ‘number_t*’ {aka ‘float*’} to ‘double*’
   55 |     cs_lsolve(N->L, x);         /* x = L\x */
      |                     ^
      |                     |
      |                     number_t* {aka float*}
In file included from /home/administrator/Downloads/packages/libg2o-release/g2o/solvers/csparse/csparse_extension.h:27,
                 from /home/administrator/Downloads/packages/libg2o-release/g2o/solvers/csparse/csparse_extension.cpp:21:
/usr/include/suitesparse/cs.h:137:43: note:   initializing argument 2 of ‘int cs_di_lsolve(const cs_di*, double*)’
  137 | int cs_di_lsolve (const cs_di *L, double *x) ;
      |                                   ~~~~~~~~^
/home/administrator/Downloads/packages/libg2o-release/g2o/solvers/csparse/csparse_extension.cpp:56:22: error: cannot convert ‘number_t*’ {aka ‘float*’} to ‘double*’
   56 |     cs_ltsolve(N->L, x);        /* x = L'\x */
      |                      ^
      |                      |
      |                      number_t* {aka float*}
In file included from /home/administrator/Downloads/packages/libg2o-release/g2o/solvers/csparse/csparse_extension.h:27,
                 from /home/administrator/Downloads/packages/libg2o-release/g2o/solvers/csparse/csparse_extension.cpp:21:
/usr/include/suitesparse/cs.h:138:44: note:   initializing argument 2 of ‘int cs_di_ltsolve(const cs_di*, double*)’
  138 | int cs_di_ltsolve (const cs_di *L, double *x) ;
      |                                    ~~~~~~~~^
/home/administrator/Downloads/packages/libg2o-release/g2o/solvers/csparse/csparse_extension.cpp:57:22: error: cannot convert ‘number_t*’ {aka ‘float*’} to ‘const double*’
   57 |     cs_pvec(S->pinv, x, b, n);  /* b = P'*x */
      |                      ^
      |                      |
      |                      number_t* {aka float*}
In file included from /home/administrator/Downloads/packages/libg2o-release/g2o/solvers/csparse/csparse_extension.h:27,
                 from /home/administrator/Downloads/packages/libg2o-release/g2o/solvers/csparse/csparse_extension.cpp:21:
/usr/include/suitesparse/cs.h:143:45: note:   initializing argument 2 of ‘int cs_di_pvec(const int*, const double*, double*, int)’
  143 | int cs_di_pvec (const int *p, const double *b, double *x, int n) ;
      |                               ~~~~~~~~~~~~~~^
/home/administrator/Downloads/packages/libg2o-release/g2o/solvers/csparse/csparse_extension.cpp: In function ‘cs_din* g2o::csparse_extension::cs_chol_workspace(const cs_di*, const cs_dis*, int*, number_t*)’:
/home/administrator/Downloads/packages/libg2o-release/g2o/solvers/csparse/csparse_extension.cpp:87:11: error: cannot convert ‘double*’ to ‘number_t*’ {aka ‘float*’} in assignment
   87 |   Cx = C->x;
      |        ~~~^
      |           |
      |           double*
/home/administrator/Downloads/packages/libg2o-release/g2o/solvers/csparse/csparse_extension.cpp:92:11: error: cannot convert ‘double*’ to ‘number_t*’ {aka ‘float*’} in assignment
   92 |   Lx = L->x;
      |        ~~~^
      |           |
      |           double*
make[2]: *** [g2o/solvers/csparse/CMakeFiles/csparse_extension.dir/build.make:90: g2o/solvers/csparse/CMakeFiles/csparse_extension.dir/csparse_extension.cpp.o] Error 1
make[2]: Leaving directory '/home/administrator/Downloads/packages/libg2o-release/build'
make[1]: *** [CMakeFiles/Makefile2:1761: g2o/solvers/csparse/CMakeFiles/csparse_extension.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/administrator/Downloads/packages/libg2o-release/build'
[ 20%] Built target interface_library

Does G2O_SINGLE_PRECISION_MATH supported ? and how resolve compilation errors ?
Thanks
Dima

**Comment by RainerKuemmerle** [comment]
G2O_SINGLE_PRECISION_MATH was broken and I recently removed the feature from master.
