### ISSUE TITLE
error: ‘number_t’ does not name a type; did you mean ‘timer_t’?

### ISSUE THREAD

**Issue by wfw869** [RainerKuemmerle/g2o#703]
G2o is complied successfully, but G2O has error: ‘number_t’ does not name a type; did you mean ‘timer_t’? in g2o/g2o/core/eigen_types.h when I use it. How can I do?

**Comment by RainerKuemmerle** [comment]
number_t is removed from the global scope. I would recommend to change code to not use number_t.
The typedef should still be available as g2o::number_t. See
https://github.com/RainerKuemmerle/g2o/blob/master/g2o/core/eigen_types.h#L36
