### ISSUE TITLE
void g2o::HyperGraph::Edge::setVertex(size_t, g2o::HyperGraph::Vertex*): Assertion `i < _vertices.size() && "index out of bounds"' failed.

### ISSUE THREAD

**Issue by yangliu9527** [RainerKuemmerle/g2o#720]
The multiedge I defined as below:
`class EdgeCamPoseObjPoseMpPos : public g2o::BaseMultiEdge<2, Eigen::Vector2d>`
 `{public:`
  `EIGEN_MAKE_ALIGNED_OPERATOR_NEW`
  `EdgeCamPoseObjPoseMpPos(GeometricCamera *pCamera_) : pCamera(pCamera_)`
  `{ }`
  `void computeError();`
  `virtual void linearizeOplus();`
  `virtual bool read(std::istream &is) { return false; }`
  `virtual bool write(std::ostream &os) const { return false; }`
  `GeometricCamera *pCamera;`
  `};`

The code I set vertex for the edge as below:
`g2o::HyperGraph::Vertex* VCamPose = optimizer.vertex(mFrameId_Frame[ObsFrameId].mnId);`
`g2o::HyperGraph::Vertex* VObjPose = optimizer.vertex(mObj3D_mObsFrameId_PoseVertexId[pObj3D][ObsFrameId]);`
`g2o::HyperGraph::Vertex* VObjMp = optimizer.vertex(mObjMps_VertexId[pObjMp]);`
`e->setVertex(0, dynamic_cast<g2o::OptimizableGraph::Vertex *>(VCamPose));`
`e->setVertex(1, dynamic_cast<g2o::OptimizableGraph::Vertex *>(VObjPose));`
`e->setVertex(2, dynamic_cast<g2o::OptimizableGraph::Vertex *>(VObjMp));`

The compiling succeeds but when perform  `e->setVertex(0,dynamic_cast<g2o::OptimizableGraph::Vertex *>(VCamPose));`, an error occurs:
 g2o/g2o/types/../core/hyper_graph.h:148: void g2o::HyperGraph::Edge::setVertex(size_t, g2o::HyperGraph::Vertex*): Assertion `i < _vertices.size() && "index out of bounds"' failed.

Do the the Vertices of MultiEdge need to be set following an order? But there are no vertex class type parameters when defining an MultiEdge. 
Please check the problem

**Comment by RainerKuemmerle** [comment]
Your code is using a BaseMultiEdge. You at some point need to resize to
your desired number of vertices your edge shall connect. For example, in
the c'tor of your edge.

If it is not working please provide a working minimal example that can be
compiled.

yangliu9527 ***@***.***> schrieb am Mi., 6. Sept. 2023, 14:58:

**Comment by yangliu9527** [comment]
@RainerKuemmerle Appreciate your reply. I have solved the problem according to your suggestion, just add a 'resize(n);' in the constructor of the edge. Thanks a lot!
