### ISSUE TITLE
LGPL3+ for csparse_extension: still up to date?

### ISSUE THREAD

**Issue by simbeta** [RainerKuemmerle/g2o#743]
## Clarification about licensing status

Is csparse_extension still under LGPL3+ as reported in the [README.md](https://github.com/RainerKuemmerle/g2o/blob/master/README.md)?
Or is the module under the terms of the GNU Lesser General Public License as reported in the [license notes of the scripts](https://github.com/RainerKuemmerle/g2o/blob/master/g2o/solvers/csparse/csparse_extension.h)?

**Comment by RainerKuemmerle** [comment]
The license in the code says LGPL v2.1+. The extension is trivial and I don't mind. Lets align README to the original license.
