### ISSUE TITLE
[error] [optimizable_graph.cpp:483] virtual bool 

### ISSUE THREAD

**Issue by bowei20222023** [RainerKuemmerle/g2o#762]
I have seen this errors using the recent version when using g2o_viewer to load g2o file. 
My computer is Macbook pro with M1 pro chip. I am using vitural machine software parallel with Ubuntu 22.04LTS.
g2o_viewer  and g2o have been successfully installed in Ubuntu 22.04LTS. But the following errors happens.

[2024-02-20 13:22:08.748] [g2o] [error] [optimizable_graph.cpp:483] virtual bool g2o::OptimizableGraph::load(std::istream&): Unable to find vertices for edge EDGE_SE2 at line 32918 IDs: 3928 1766

<img width="729" alt="image" src="https://github.com/RainerKuemmerle/g2o/assets/124149812/3c72fba5-c431-4326-90ae-6270b73ebdda">

I also tried the same g2o file in my old computer with old version of g2o_viewer, which works fine

**Comment by RainerKuemmerle** [comment]
Would it be possible to get the g2o file for debugging?Am 20.02.2024 um 14:31 schrieb bowei20222023 ***@***.***>:﻿
I have seen this errors using the recent version when using g2o_viewer to load g2o file.
My computer is Macbook pro with M1 pro chip. I am using vitural machine software parallel with Ubuntu 22.04LTS.
g2o_viewer  and g2o have been successfully installed in Ubuntu 22.04LTS. But the following errors happens.
[2024-02-20 13:22:08.748] [g2o] [error] [optimizable_graph.cpp:483] virtual bool g2o::OptimizableGraph::load(std::istream&): Unable to find vertices for edge EDGE_SE2 at line 32918 IDs: 3928 1766
image.png (view on web)
I also tried the same g2o file in my old computer with old version of g2o_viewer, which works fine
