### ISSUE TITLE
Problem related to freeglut library while setting G2O_USE_OPENGL off in CMAKE

### ISSUE THREAD

**Issue by Smithangshu** [RainerKuemmerle/g2o#779]
Hi Rainer,

Thank you for your effort to develop this great library. I am using it since long time. I last build it with CMAKE and VC on the end of 2021 then, I did not have any issue. But in current version I am facing an issue like when I am setting the flag G2O_USE_OPENGL to off and build it. Then everything goes smoothly but when I am using it in my project, I am seeing an error that is,

LNK1104	cannot open file 'g2o_ext_freeglut_minimal.lib'

But I think we should not need this library when we are not using OpenGL. But it's happening. And in previous version, which was working, did not have any flag to turn off OpenGL usage. So, it was building "freeglut_minimal" project, I see this project is listed within the g2o solution in Visual Studio.

So, cannot we use g2o without using OpenGL?

**Comment by RainerKuemmerle** [comment]
How are you setting up your build? I could not spot freeglut_minimal being specified in the exported cmake targets when building with G2O_USE_OPENGL = OFF.
