### ISSUE TITLE
VectorXD in LinearSolverEigen

### ISSUE THREAD

**Issue by raulmur** [RainerKuemmerle/g2o#78]
https://github.com/RainerKuemmerle/g2o/blob/master/g2o/solvers/eigen/linear_solver_eigen.h#L112-L113

Shouldn't it be VectorXd ?

**Comment by RainerKuemmerle** [comment]
VectorXD is a typedef inside the g2o namespace.
Are you running in any compilation issues?

**Comment by raulmur** [comment]
I added the eigen solver to an older g2o version without the eigen_types.h
Thanks!
