### ISSUE TITLE
Error on optimizer.vertices().find(j)->second

### ISSUE THREAD

**Issue by KibaekPark** [RainerKuemmerle/g2o#79]
Hello,
I compiled g2o by using instruction as follows:
$ -mkdir build
$ -cd build
$ -cmake ../
$ -make
And built example($ ./ba_demo) works well.
now, I am compiling g2o on QT project in QT Creator 5.5. I am successfully compiling g2o on QT, However, while running a example code;ba_demo.cpp, There is segmentation fault error in "optimizer.vertices().find(j)->second" . I found a problem on find(), _M_find_before_node and _M_buckets. Specifically, segmentation fault error in _BaseNode\* __prev_p = _M_buckets[__n]; (unordered_map)
Is it compile setup problem?

---

my *.pro as follows:

QT       += core
QT       -= gui

TARGET = g2o_qtTest
CONFIG   += console
CONFIG   -= app_bundle

TEMPLATE = app

SOURCES += main.cpp
# QMAKE_CXXFLAGS += -std=c++11
# QMAKE_CXXFLAGS += -D_GLIBCXX_DEBUG
# QMAKE_CXXFLAGS += -std=c++0x

QMAKE_CXXFLAGS += -std=gnu++0x
# CONFIG += c++11

INCLUDEPATH += /usr/include/opencv
INCLUDEPATH += /usr/include/eigen3/Eigen
INCLUDEPATH += /home/kb/Workspace/g2o/g2o-master/lib/
INCLUDEPATH += /home/kb/Workspace/g2o/g2o-master/

LIBS += `pkg-config opencv –cflags –libs`
LIBS += -lopencv_core
LIBS += -lopencv_imgproc
LIBS += -lopencv_highgui
LIBS += -lopencv_ml
LIBS += -lopencv_video
LIBS += -lopencv_features2d
LIBS += -lopencv_calib3d
LIBS += -lopencv_objdetect
LIBS += -lopencv_contrib
LIBS += -lopencv_legacy
LIBS += -lopencv_flann
# LIBS += -lopencv_nonfree

LIBS += -lceres -lcsparse -lcholmod -fopenmp -lcblas -lblas -llapack
LIBS += -lboost_system

LIBS += -L/home/kb/Workspace/g2o/g2o-master/lib/
LIBS += -lg2o_calibration_odom_laser
LIBS += -lg2o_cli
LIBS += -lg2o_core
LIBS += -lg2o_csparse_extension
LIBS += -lg2o_ext_freeglut_minimal
LIBS += -lg2o_hierarchical
LIBS += -lg2o_incremental
LIBS += -lg2o_interactive
LIBS += -lg2o_opengl_helper
LIBS += -lg2o_interface
LIBS += -lg2o_parser
LIBS += -lg2o_simulator
LIBS += -lg2o_solver_cholmod
LIBS += -lg2o_solver_csparse
LIBS += -lg2o_solver_dense
LIBS += -lg2o_solver_eigen
LIBS += -lg2o_solver_pcg
LIBS += -lg2o_solver_slam2d_linear
LIBS += -lg2o_solver_structure_only
LIBS += -lg2o_stuff
LIBS += -lg2o_tutorial_slam2d
LIBS += -lg2o_types_data
LIBS += -lg2o_types_icp
LIBS += -lg2o_types_sba
LIBS += -lg2o_types_sclam2d
LIBS += -lg2o_types_sim3
LIBS += -lg2o_types_slam2d
LIBS += -lg2o_types_slam2d_addons
LIBS += -lg2o_types_slam3d
LIBS += -lg2o_types_slam3d_addons

INCLUDEPATH += /usr/include/suitesparse/

**Comment by RainerKuemmerle** [comment]
Can you provide some example code? Did you just copy and compile ba_demo using a Qt project?
