### ISSUE TITLE
[g2opy] Error when loading .g2o file using optimizer.load() function

### ISSUE THREAD

**Issue by Lky0724** [RainerKuemmerle/g2o#793]
I am trying to run [notebook_slam2d.ipynb](https://github.com/RainerKuemmerle/g2o/blob/pymem/python/examples/notebook_slam2d.ipynb) in pymem branch to learn to use g2o. But something went wrong when I try to load the pose graph, which was stored in a .g2o file under the same directory, into the optimizer. Even though no error was reported, it seems that the file is not successfully loaded (returned number of vertices and edges are 0), and the visualization of the data in the following part also shows nothing.

Below is the code and output.

```
optimizer.clear()
optimizer.load("manhattanOlson3500.g2o")
print(f"Number of vertices: {len(optimizer.vertices())}")
print(f"Number of edges {len(optimizer.edges())}")
```
> Number of vertices: 0
Number of edges 0

What can I do with it? Besides, is there a detailed documentation of the avaliable functions in g2o and its python binding? 
Thank you very much for your help!

**Comment by RainerKuemmerle** [comment]
Which version of g2o did you compile/use? It might be related to https://github.com/RainerKuemmerle/g2o/pull/764 - maybe there is yet another issue.
