### ISSUE TITLE
Build error on ubuntu 20.04

### ISSUE THREAD

**Issue by Lky0724** [RainerKuemmerle/g2o#794]
I am trying to build g2o on ubuntu 20.04 using following command:

```
mkdir build
cd build
cmake ../
make
```
But I always encounter following error when I execute 'make' order:

> /usr/bin/ld: CMakeFiles/slam2d_g2o.dir/slam2d_viewer.cpp.o: in function `g2o::Slam2DViewer::Slam2DViewer(QWidget*, QGLWidget const*)':
slam2d_viewer.cpp:(.text+0x26b): undefined reference to `QGLViewer::QGLViewer(QWidget*, QGLWidget const*, QFlags<Qt::WindowType>)'
collect2: error: ld returned 1 exit status

I have successfully installed all the required dependencies listed in [README](https://github.com/RainerKuemmerle/g2o/blob/master/README.md), what else is missing? How can I solve the problem?

**Comment by RainerKuemmerle** [comment]
I successfully tested building in an uptodate Ubuntu 20.04 container running on and64 architecture.

Below is the version of libqglviewer being used

```
$ apt-cache policy libqglviewer-dev-qt5
libqglviewer-dev-qt5:
  Installed: 2.6.3+dfsg2-6build1
  Candidate: 2.6.3+dfsg2-6build1
  Version table:
 *** 2.6.3+dfsg2-6build1 500
        500 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages
        100 /var/lib/dpkg/status
```
