### ISSUE TITLE
Landmark-pose constraint compatibility in g2o for 3D SLAM

### ISSUE THREAD

**Issue by RachitB11** [RainerKuemmerle/g2o#92]
I have both estimates of the landmark in some frames of robot poses (encoded in the type EDGE_SE3_TRACKXYZ) and also the estimate of the landmark in the world frame (encoded in the type VERTEX_TRACKXYZ). The pose-pose constraints are detected very well by the g2o_viewer but the landmark-pose constraints in particular throws a bad_typeid exception.

Are Landmark-pose edges in 3D not supported by the g2o_viewer? Is EDGE_SE3_TRACKXYZ the wrong type?

**Comment by kanster** [comment]
Hi RachitB11, 

Landmark-pose edge in 3d is supported by g2o and EDGE_SE3_TRACKXYZ is the correct type

You may face the same issue as https://github.com/RainerKuemmerle/g2o/issues/34

Please add another parameter and link each edge to the parameter
