### ISSUE TITLE
SOLVED: OPENGL_gl_LIBRARY linked by target "simulator_3d_plane" NOTFOUND

### ISSUE THREAD

**Issue by bashbug** [RainerKuemmerle/g2o#93]
Android cross compiling g2o crashes with the following error:

> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> Please set them or make sure they are set and tested correctly in the CMake files:
> OPENGL_gl_LIBRARY (ADVANCED)
>     linked by target "simulator_3d_plane" in directory /home/anastasia/g2o/g2o/examples/plane_slam
> 
> -- Configuring incomplete, errors occurred!

It can be solved by testing if Open GL is available before adding plane_slam (/g2o/g2o/examples/CMakeLists.txt): 

> IF(OPENGL_FOUND AND CSPARSE_FOUND)
>   ADD_SUBDIRECTORY(plane_slam)
> ENDIF()

**Comment by RainerKuemmerle** [comment]
Thanks for reporting this. I removed the explicit linking to the OpenGL, see 41b0be79a0821c1466f694dc16a9ee2c5ee92a9b
I hope this also fixes the issue.
