### ISSUE TITLE
Symbols missing in csparse_extension

### ISSUE THREAD

**Issue by ningt** [RainerKuemmerle/g2o#95]
Hi I try to use g2o in xcode, but I got errors like the following:
```
Undefined symbols for architecture x86_64:
  "g2o::csparse_extension::cs_cholsolsymb(cs_di_sparse const*, double*, cs_di_symbolic const*, double*, int*)", referenced from:
      g2o::LinearSolverCSparse<Eigen::Matrix<double, 7, 7, 0, 7, 7> >::solve(g2o::SparseBlockMatrix<Eigen::Matrix<double, 7, 7, 0, 7, 7> > const&, double*, double*) in KeyFrameGraph.o
```

It seems that something wrong with suite-sparse build. I installed suite-sparse from homebrew (it downloads suite-sparse from http://faculty.cse.tamu.edu/davis/suitesparse.html) and I found the link for suite-sparse in README.md is broken.

Any suggestions?

**Comment by felixendres** [comment]
Do you specify to link against libg2o_csparse_extension.so? If you use cmake, add `${G2O_SOLVER_CSPARSE_EXTENSION}` to the call of `target_link_libraries` for your target.

**Comment by ningt** [comment]
I am using Xcode, and I think already linked against `libg2o_csparse_extension`.

<img width="859" alt="screen shot 2016-01-26 at 11 02 12 pm" src="https://cloud.githubusercontent.com/assets/5404896/12584137/045aa600-c481-11e5-952f-6ba110d3bc57.png">

**Comment by felixendres** [comment]
The symbol (function) actually comes from g2o. It is in csparse_helpers.h/cpp. According to the makefile it should be in libg2o_csparse_extensions.so, but I've checked its symbol table (`readelf -s libg2o...`) and it doesn't show up. I don't know why. But I guess that it has nothing to do with SuiteSparse.

**Comment by ningt** [comment]
Since it's not related to SuiteSparse, I updated the title of this issue. Do you have any suggestions about this? Thanks.

**Comment by hongyan90** [comment]
Hi, I met this question,too. If you have solved this question, could you give me some suggestions?

**Comment by alibenD** [comment]
Does anyone has a solution for it now? I met this question, too.

**Comment by songyongkang** [comment]
> Since it's not related to SuiteSparse, I updated the title of this issue. Do you have any suggestions about this? Thanks.

Does anyone has a solution for it now? I met this question, too.
